In [25]:
import os
import polars as pl

In [26]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
features_dir = os.path.join(project_path, 'data', 'features')
feature_file_path = os.path.join(features_dir, 'content_relevance_score.parquet')
feature_df = pl.read_parquet(feature_file_path)

In [27]:
# 1. Mostrar el contenido completo de los strings (sin límite)
pl.Config.set_fmt_str_lengths(1000) # Ajusta al largo que necesites

polars.config.Config

197_000, $

In [28]:
feature_df

shape: (199_000, 3)
┌────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_score                         │
│ ---        ┆ ---                     ┆ ---                                                       │
│ str        ┆ i64                     ┆ str                                                       │
╞════════════╪═════════════════════════╪═══════════════════════════════════════════════════════════╡
│ mzlqxrg    ┆ 4                       ┆ The comment expresses a desire for Iran to take military  │
│            ┆                         ┆ action against Israel in the context of humanitarian aid, │
│            ┆                         ┆ which relates directly to the ongoing conflict and its    │
│            ┆                         ┆ implications for Gaza.                                    │
│ obbcoq3    ┆ 0                       ┆ The comment is vague and does not provide any specific    │
│            ┆                         ┆ information or opinion related to the Gaza conflict,      │
│            ┆                         ┆ focusing instead on a general statement about truth       │
│            ┆                         ┆ without context.                                          │
│ n9yjtzg    ┆ 2                       ┆ The comment reflects on the hostility faced by Jews in    │
│            ┆                         ┆ Barcelona, linking it to broader themes of antisemitism   │
│            ┆                         ┆ and public sentiment related to the Gaza conflict, but it │
│            ┆                         ┆ does not directly address the conflict itself or its core │
│            ┆                         ┆ events.                                                   │
│ nax2wzf    ┆ 1                       ┆ The comment focuses on a political strategy regarding the │
│            ┆                         ┆ Democratic Party in the context of the Gaza conflict, but │
│            ┆                         ┆ it does not directly address the humanitarian situation   │
│            ┆                         ┆ or the core events of the conflict itself. It is more     │
│            ┆                         ┆ about U.S. internal politics than the Gaza conflict.      │
│ n8vxcji    ┆ 3                       ┆ The comment reflects on a historical event related to     │
│            ┆                         ┆ Israel's actions in Gaza and connects it to current       │
│            ┆                         ┆ events, indicating a perspective on the conflict's        │
│            ┆                         ┆ implications. However, it does not engage with the core   │
│            ┆                         ┆ conflict or humanitarian issues directly.                 │
│ …          ┆ …                       ┆ …                                                         │
│ n10aq2v    ┆ 5                       ┆ The comment explicitly discusses the ongoing violence and │
│            ┆                         ┆ humanitarian implications of the conflict, focusing on    │
│            ┆                         ┆ the actions of Israel and Hamas, which are central to the │
│            ┆                         ┆ Gaza conflict.                                            │
│ mwt71mo    ┆ 5                       ┆ The comment discusses the situation in Gaza, including    │
│            ┆                         ┆ the implications of journalist access and the actions of  │
│            ┆                         ┆ Hamas, which are directly related to the core conflict    │
│            ┆                         ┆ and the humanitarian situation in the region.             │
│ nk1nmy7    ┆ 1                       ┆ The comment primarily focuses on a specific individual    │
│            ┆                         ┆ accused of hate crimes and expresses disdain for public   │
│            ┆                         ┆ support of him, but it does not directly address the Gaza │
│            ┆                         ┆ conflict or its core issues. Instead, it veers into       │
│            ┆                         ┆ personal attacks and generalizations about public         │
│            ┆                         ┆ opinion, which are not relevant to the conflict itself.   │
│ o0clris    ┆ 5                       ┆ The comment expresses strong emotions regarding the       │
│            ┆                         ┆ humanitarian crisis in Gaza, specifically mentioning the  │
│            ┆                         ┆ suffering of civilians and the actions of the IDF, which  │
│            ┆                         ┆ are directly related to the core conflict.                │
│ nhqw79j    ┆ 0                       ┆ The comment does not provide any relevant information or  │
│            ┆                         ┆ context regarding the Gaza conflict and instead poses a   │
│            ┆                         ┆ vague question, making it unrelated to the topic.         │
└────────────┴─────────────────────────┴───────────────────────────────────────────────────────────┘

In [18]:
count_relevant_content = sum(feature_df['content_relevance_score'] >= 3) 
content_size = len(feature_df)
prop_relevant_content = count_relevant_content / content_size
print(f"Count relevant content: {count_relevant_content}")
print(f"Percentage relevant content: {round(prop_relevant_content * 100, 2)}%")

Count relevant content: 97269
Percentage relevant content: 49.08%

In [19]:
feature_df['content_relevance_score'].value_counts().sort('count', descending=True)

shape: (7, 2)
┌─────────────────────────┬───────┐
│ content_relevance_score ┆ count │
│ ---                     ┆ ---   │
│ i64                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 4                       ┆ 46014 │
│ 0                       ┆ 44584 │
│ 2                       ┆ 33395 │
│ 5                       ┆ 26572 │
│ 3                       ┆ 24683 │
│ 1                       ┆ 22946 │
│ -1                      ┆ 6     │
└─────────────────────────┴───────┘

In [20]:
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')

base_data_path = os.path.join(processed_data_dir, '02_processed_data.parquet') 

base_df = pl.read_parquet(base_data_path)

processed_df = base_df.join(feature_df, how='left', on='comment_id')

processed_df = processed_df[['comment_id', 'post_id', 'post_title', 'post_body', 'comment_body', 'content_relevance_score', 'reasoning_content_relevance_score']]

In [24]:
len(processed_df) - processed_df['content_relevance_score'].is_null().sum()

198200

In [35]:
for score in processed_df['content_relevance_score'].unique():
    if score:
        print(f'content_relevance_score == {score}'.upper())
        display(processed_df.filter(pl.col('content_relevance_score') == score).sample(n=5, seed=123))
        print('='*200, '\n')

CONTENT_RELEVANCE_SCORE == -1

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ n8mj7ql    ┆ 1mpr8o4 ┆ a video of    ┆              ┆ **Looks like ┆ -1           ┆ The comment  │
│            ┆         ┆ aljazera      ┆              ┆ this thread  ┆              ┆ is           │
│            ┆         ┆ journalist    ┆              ┆ is getting a ┆              ┆ meta-Reddit  │
│            ┆         ┆ Anas, who was ┆              ┆ lot of       ┆              ┆ moderation/a │
│            ┆         ┆ killed by     ┆              ┆ attention.   ┆              ┆ ttention (   │
│            ┆         ┆ Israel,       ┆              ┆ Greetings,   ┆              ┆              │
│            ┆         ┆ talking to    ┆              ┆ /r/all!      ┆              ┆              │
│            ┆         ┆ his daughter  ┆              ┆ Please keep  ┆              ┆              │
│            ┆         ┆ Sham.         ┆              ┆ it civil.**  ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆ *I am a bot, ┆              ┆              │
│            ┆         ┆               ┆              ┆ and this     ┆              ┆              │
│            ┆         ┆               ┆              ┆ action was   ┆              ┆              │
│            ┆         ┆               ┆              ┆ performed    ┆              ┆              │
│            ┆         ┆               ┆              ┆ automaticall ┆              ┆              │
│            ┆         ┆               ┆              ┆ y. Please    ┆              ┆              │
│            ┆         ┆               ┆              ┆ [contact the ┆              ┆              │
│            ┆         ┆               ┆              ┆ moderators   ┆              ┆              │
│            ┆         ┆               ┆              ┆ of this subr ┆              ┆              │
│            ┆         ┆               ┆              ┆ eddit](/mess ┆              ┆              │
│            ┆         ┆               ┆              ┆ age/compose/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ ?to=/r/Pales ┆              ┆              │
│            ┆         ┆               ┆              ┆ tine) if you ┆              ┆              │
│            ┆         ┆               ┆              ┆ have any     ┆              ┆              │
│            ┆         ┆               ┆              ┆ questions or ┆              ┆              │
│            ┆         ┆               ┆              ┆ concerns.*   ┆              ┆              │
│ npf2aoc    ┆ 1ozxpc4 ┆ At least on   ┆              ┆ Something,   ┆ -1           ┆ The comment  │
│            ┆         ┆ Reddit,       ┆              ┆ something,   ┆              ┆ is a terse,  │
│            ┆         ┆ pro-Palestine ┆              ┆ projection   ┆              ┆ generic      │
│            ┆         ┆ subs do not   ┆              ┆ is the word  ┆              ┆ rebuttal (   │
│            ┆         ┆ say/discuss   ┆              ┆ that is      ┆              ┆              │
│            ┆         ┆ 'Globalize    ┆              ┆ appropriate  ┆              ┆              │
│            ┆         ┆ the Intifada' ┆              ┆ here.        ┆              ┆              │
│            ┆         ┆ much. But     ┆              ┆              ┆              ┆              │
│            ┆         ┆ pro-Israel    ┆              ┆              ┆              ┆              │
│            ┆         ┆ subs          ┆              ┆              ┆              ┆              │
│            ┆         ┆ absolutely do ┆              ┆              ┆              ┆              │
│            ┆         ┆ & obsess      ┆              ┆              ┆              ┆              │
│            ┆         ┆ about it. The ┆              ┆              ┆              ┆              │
│            ┆         ┆ 'controversy' ┆              ┆              ┆              ┆              │
│            ┆         ┆ over this     ┆              ┆              ┆              ┆              │
│            ┆         ┆ expression is ┆              ┆              ┆              ┆              │
│            ┆         ┆ exaggerated & ┆              ┆              ┆              ┆              │
│            ┆         ┆ weaponized to ┆              ┆              ┆              ┆              │
│            ┆         ┆ slander       ┆              ┆              ┆              ┆              │
│            ┆         ┆ critics of    ┆              ┆              ┆              ┆              │
│            ┆         ┆ Israel as     ┆              ┆              ┆              ┆              │
│            ┆         ┆ antisemitic.  ┆              ┆              ┆              ┆              │
│ ocakh06    ┆ 1s2nzvc ┆ I hope they   ┆ Infront of   ┆ Oh they      ┆ -1           ┆ Primary      │
│            ┆         ┆ realise the   ┆ Elstree and  ┆ realise      ┆              ┆ subject:     │
│            ┆         ┆ truth that    ┆ Borehamwood  ┆              ┆              ┆ accusation   │
│            ┆         ┆ they are      ┆ station,     ┆              ┆              ┆ of           │
│            ┆         ┆ supporting a  ┆ London, UK.  ┆              ┆              ┆ supporting a │
│            ┆         ┆ gncidl        ┆              ┆              ┆              ┆ 'genocidal   │
│            ┆         ┆ entity.       ┆              ┆              ┆              ┆ entity'      │
│            ┆         ┆               ┆              ┆              ┆              ┆ (core        │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza/Israel  │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict) at │
│            ┆         ┆               ┆              ┆              ┆              ┆ a London     │
│            ┆         ┆               ┆              ┆              ┆              ┆ location;    │
│            ┆         ┆               ┆              ┆              ┆              ┆ the comment  │
│            ┆         ┆               ┆              ┆              ┆              ┆ (            │
│ n7xwa20    ┆ 1mm4i9x ┆ If Pro-Palest ┆ I often hear ┆ Couldn't     ┆ -1           ┆ The comment  │
│            ┆         ┆ inians think  ┆ Pro-Palestin ┆ agree more.  ┆              ┆ is a         │
│            ┆         ┆ "Zionism" is  ┆ ian say      ┆              ┆              ┆ one-line     │
│            ┆         ┆ an ideology   ┆ things like  ┆              ┆              ┆ expression   │
│            ┆         ┆ rather than a ┆ "I don't     ┆              ┆              ┆ of agreement │
│            ┆         ┆ reference to  ┆ hate Jews, I ┆              ┆              ┆ (            │
│            ┆         ┆ Jews, then    ┆ just hate    ┆              ┆              ┆              │
│            ┆         ┆ why do they   ┆ Zionists."   ┆              ┆              ┆              │
│            ┆         ┆ call all Jews ┆ They explain ┆              ┆              ┆              │
│            ┆         ┆ who moved to  ┆ that         ┆              ┆              ┆              │
│            ┆         ┆ Israel        ┆ "Zionists"   ┆              ┆              ┆              │
│            ┆         ┆ "Zionists"?   ┆ were a       ┆              ┆              ┆              │
│            ┆         ┆               ┆ political    ┆              ┆              ┆              │
│            ┆         ┆               ┆ movement to  ┆              ┆              ┆              │
│            ┆         ┆               ┆ displace     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Arabs or     ┆              ┆              ┆              │
│            ┆         ┆               ┆ something,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ totally      ┆              ┆              ┆              │
│            ┆         ┆               ┆ separate     ┆              ┆              ┆              │
│            ┆         ┆               ┆ from the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ ethnicity    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and religion ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Judaism.  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ If that were ┆              ┆              ┆              │
│            ┆         ┆               ┆ true, then   ┆              ┆              ┆              │
│            ┆         ┆               ┆ why do they  ┆              ┆              ┆              │
│            ┆         ┆               ┆ call any     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jews who     ┆              ┆              ┆              │
│            ┆         ┆               ┆ moved to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel       ┆              ┆              ┆              │
│            ┆         ┆               ┆ "Zionists"?  ┆              ┆              ┆              │
│            ┆         ┆               ┆ For          ┆              ┆              ┆              │
│            ┆         ┆               ┆ instance,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ they say     ┆              ┆              ┆              │
│            ┆         ┆               ┆ things like  ┆              ┆              ┆              │
│            ┆         ┆               ┆ "Hundreds of ┆              ┆              ┆              │
│            ┆         ┆               ┆ thousands of ┆              ┆              ┆              │
│            ┆         ┆               ┆ Zionist      ┆              ┆              ┆              │
│            ┆         ┆               ┆ colonizers   ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrated   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to Israel in ┆              ┆              ┆              │
│            ┆         ┆               ┆ the 1800s    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and 1900s"   ┆              ┆              ┆              │
│            ┆         ┆               ┆ even though  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the majority ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Jews who  ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrated   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to Israel    ┆              ┆              ┆              │
│            ┆         ┆               ┆ were         ┆              ┆              ┆              │
│            ┆         ┆               ┆ refugees who ┆              ┆              ┆              │
│            ┆         ┆               ┆ had no       ┆              ┆              ┆              │
│            ┆         ┆               ┆ particular   ┆              ┆              ┆              │
│            ┆         ┆               ┆ political    ┆              ┆              ┆              │
│            ┆         ┆               ┆ agenda.      ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ There were   ┆              ┆              ┆              │
│            ┆         ┆               ┆ certainly    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jews who     ┆              ┆              ┆              │
│            ┆         ┆               ┆ dreamed of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ some kind of ┆              ┆              ┆              │
│            ┆         ┆               ┆ vague        ┆              ┆              ┆              │
│            ┆         ┆               ┆ homeland in  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel —     ┆              ┆              ┆              │
│            ┆         ┆               ┆ originally   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the dream    ┆              ┆              ┆              │
│            ┆         ┆               ┆ was to be    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Ottoman      ┆              ┆              ┆              │
│            ┆         ┆               ┆ subjects     ┆              ┆              ┆              │
│            ┆         ┆               ┆ living in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the Ottoman  ┆              ┆              ┆              │
│            ┆         ┆               ┆ empire in    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewish neigh ┆              ┆              ┆              │
│            ┆         ┆               ┆ borhoods,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ later when   ┆              ┆              ┆              │
│            ┆         ┆               ┆ hundreds of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ groups       ┆              ┆              ┆              │
│            ┆         ┆               ┆ started      ┆              ┆              ┆              │
│            ┆         ┆               ┆ dreaming of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ a nation     ┆              ┆              ┆              │
│            ┆         ┆               ┆ state, Jews  ┆              ┆              ┆              │
│            ┆         ┆               ┆ did too —    ┆              ┆              ┆              │
│            ┆         ┆               ┆ but the      ┆              ┆              ┆              │
│            ┆         ┆               ┆ reality is,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ most Jews    ┆              ┆              ┆              │
│            ┆         ┆               ┆ moved to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ escape       ┆              ┆              ┆              │
│            ┆         ┆               ┆ persecution. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ For          ┆              ┆              ┆              │
│            ┆         ┆               ┆ instance, in ┆              ┆              ┆              │
│            ┆         ┆               ┆ the 1880s,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ most Jewish  ┆              ┆              ┆              │
│            ┆         ┆               ┆ immigrants   ┆              ┆              ┆              │
│            ┆         ┆               ┆ were Russian ┆              ┆              ┆              │
│            ┆         ┆               ┆ and Romanian ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewih        ┆              ┆              ┆              │
│            ┆         ┆               ┆ refugees     ┆              ┆              ┆              │
│            ┆         ┆               ┆ fled pogroms ┆              ┆              ┆              │
│            ┆         ┆               ┆ (violent     ┆              ┆              ┆              │
│            ┆         ┆               ┆ anti-…       ┆              ┆              ┆              │
│ oaxrhwt    ┆ 1rw7k69 ┆ Mamdani rips  ┆              ┆ Mayor Shit-e ┆ -1           ┆ The comment  │
│            ┆         ┆ ‘genocide’ in ┆              ┆ ating-grin   ┆              ┆ is a short   │
│            ┆         ┆ Palestine at  ┆              ┆              ┆              ┆ insult/nickn │
│            ┆         ┆ St. Patrick’s ┆              ┆              ┆              ┆ ame (        │
│            ┆         ┆ Day event —   ┆              ┆              ┆              ┆              │
│            ┆         ┆ after he      ┆              ┆              ┆              ┆              │
│            ┆         ┆ botches       ┆              ┆              ┆              ┆              │
│            ┆         ┆ answer on     ┆              ┆              ┆              ┆              │
│            ┆         ┆ unified       ┆              ┆              ┆              ┆              │
│            ┆         ┆ Ireland       ┆              ┆              ┆              ┆              │
└────────────┴─────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 1

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ nk4k0hx    ┆ 1o9s5u1 ┆ Venezuelan    ┆              ┆ She sounds   ┆ 1            ┆ The comment  │
│            ┆         ┆ opposition    ┆              ┆ like an Arab ┆              ┆ makes a      │
│            ┆         ┆ leader and    ┆              ┆ leader. I    ┆              ┆ vague        │
│            ┆         ┆ Nobel Peace   ┆              ┆ though Latin ┆              ┆ comparison   │
│            ┆         ┆ Prize winner  ┆              ┆ American     ┆              ┆ between a    │
│            ┆         ┆ María Corina  ┆              ┆ elites had a ┆              ┆ Latin        │
│            ┆         ┆ Machado       ┆              ┆ bit more     ┆              ┆ American     │
│            ┆         ┆ voiced        ┆              ┆ honor than   ┆              ┆ leader and   │
│            ┆         ┆ support for   ┆              ┆ that. At     ┆              ┆ Arab         │
│            ┆         ┆ Israel in a   ┆              ┆ least, ever  ┆              ┆ leaders, but │
│            ┆         ┆ phone call    ┆              ┆ since the    ┆              ┆ it does not  │
│            ┆         ┆ with          ┆              ┆ American-sup ┆              ┆ directly     │
│            ┆         ┆ Netanyahu.    ┆              ┆ porter Latin ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ death squads ┆              ┆ Gaza         │
│            ┆         ┆               ┆              ┆ went into a  ┆              ┆ conflict or  │
│            ┆         ┆               ┆              ┆ decline.     ┆              ┆ provide      │
│            ┆         ┆               ┆              ┆              ┆              ┆ relevant     │
│            ┆         ┆               ┆              ┆              ┆              ┆ insights     │
│            ┆         ┆               ┆              ┆              ┆              ┆ into public  │
│            ┆         ┆               ┆              ┆              ┆              ┆ opinion      │
│            ┆         ┆               ┆              ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆              ┆              ┆              ┆ it.          │
│ nax85hs    ┆ 1n0bqox ┆ Ms Rachel's   ┆              ┆ Jesus is     ┆ 1            ┆ The comment  │
│            ┆         ┆ latest        ┆              ┆ starving in  ┆              ┆ references   │
│            ┆         ┆ "wisdom"      ┆              ┆ Gaza because ┆              ┆ historical   │
│            ┆         ┆               ┆              ┆ the Romans   ┆              ┆ events and   │
│            ┆         ┆               ┆              ┆ stole most   ┆              ┆ blames a     │
│            ┆         ┆               ┆              ┆ of the food, ┆              ┆ group for    │
│            ┆         ┆               ┆              ┆ another      ┆              ┆ the          │
│            ┆         ┆               ┆              ┆ thing that   ┆              ┆ suffering in │
│            ┆         ┆               ┆              ┆ inevitably   ┆              ┆ Gaza, but it │
│            ┆         ┆               ┆              ┆ gets blamed  ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ on the Jews. ┆              ┆ engage with  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the current  │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆              ┆              ┆              ┆ provide      │
│            ┆         ┆               ┆              ┆              ┆              ┆ relevant     │
│            ┆         ┆               ┆              ┆              ┆              ┆ insights     │
│            ┆         ┆               ┆              ┆              ┆              ┆ into public  │
│            ┆         ┆               ┆              ┆              ┆              ┆ opinion on   │
│            ┆         ┆               ┆              ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆              ┆              ┆ situation.   │
│ ngoa96l    ┆ 1ns37av ┆ Antijudaism,  ┆ If you don’t ┆ All three    ┆ 1            ┆ The comment  │
│            ┆         ┆ Antisemitism, ┆ know, then   ┆ varieties    ┆              ┆ discusses    │
│            ┆         ┆ Antizionism…  ┆ you can’t    ┆ also include ┆              ┆ conspiracy   │
│            ┆         ┆ learn to see  ┆ fight. ✡︎ 🇮🇱  ┆ the features ┆              ┆ theories in  │
│            ┆         ┆ it, learn to  ┆ ✡︎            ┆ of           ┆              ┆ relation to  │
│            ┆         ┆ name it. ✡︎    ┆              ┆ conspiracy   ┆              ┆ antisemitism │
│            ┆         ┆               ┆ The general  ┆ theory.      ┆              ┆ , which is   │
│            ┆         ┆               ┆ shape of     ┆              ┆              ┆ tangentially │
│            ┆         ┆               ┆ Jew-hate     ┆              ┆              ┆ related to   │
│            ┆         ┆               ┆ evolves and  ┆              ┆              ┆ the broader  │
│            ┆         ┆               ┆ morphs over  ┆              ┆              ┆ themes of    │
│            ┆         ┆               ┆ the decades  ┆              ┆              ┆ the post but │
│            ┆         ┆               ┆ and          ┆              ┆              ┆ does not     │
│            ┆         ┆               ┆ centuries    ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ and          ┆              ┆              ┆ address the  │
│            ┆         ┆               ┆ millennia to ┆              ┆              ┆ Gaza         │
│            ┆         ┆               ┆ fit more     ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆ modern sensi ┆              ┆              ┆ its core     │
│            ┆         ┆               ┆ bilities.    ┆              ┆              ┆ issues.      │
│            ┆         ┆               ┆ But the      ┆              ┆              ┆              │
│            ┆         ┆               ┆ results are  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the same:    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jew-hate     ┆              ┆              ┆              │
│            ┆         ┆               ┆ marginalizes ┆              ┆              ┆              │
│            ┆         ┆               ┆ and          ┆              ┆              ┆              │
│            ┆         ┆               ┆ excludes, it ┆              ┆              ┆              │
│            ┆         ┆               ┆ destroys     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jewish       ┆              ┆              ┆              │
│            ┆         ┆               ┆ communities, ┆              ┆              ┆              │
│            ┆         ┆               ┆ and it puts  ┆              ┆              ┆              │
│            ┆         ┆               ┆ our People   ┆              ┆              ┆              │
│            ┆         ┆               ┆ in harm’s    ┆              ┆              ┆              │
│            ┆         ┆               ┆ way.         ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Fight it     ┆              ┆              ┆              │
│            ┆         ┆               ┆ every single ┆              ┆              ┆              │
│            ┆         ┆               ┆ day.         ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ And teach    ┆              ┆              ┆              │
│            ┆         ┆               ┆ others how   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to see it    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and name it  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and expose   ┆              ┆              ┆              │
│            ┆         ┆               ┆ it—no matter ┆              ┆              ┆              │
│            ┆         ┆               ┆ WHERE it     ┆              ┆              ┆              │
│            ┆         ┆               ┆ comes from.  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Shana Tova.  ┆              ┆              ┆              │
│            ┆         ┆               ┆ ♥️           ┆              ┆              ┆              │
│ nqqyh0x    ┆ 1p6gykk ┆ Is            ┆ Francafrique ┆ Don’t we do  ┆ 1            ┆ The comment  │
│            ┆         ┆ Francafrique  ┆ is a term    ┆ the same     ┆              ┆ draws a      │
│            ┆         ┆ real or a     ┆ used to      ┆ shit with    ┆              ┆ parallel     │
│            ┆         ┆ conspiracy    ┆ describe     ┆ Latin        ┆              ┆ between      │
│            ┆         ┆ theory?       ┆ France’s     ┆ America?     ┆              ┆ France's     │
│            ┆         ┆ Should the US ┆ sphere of    ┆              ┆              ┆ influence in │
│            ┆         ┆ sanction      ┆ influence in ┆              ┆              ┆ its former   │
│            ┆         ┆ France for    ┆ its former   ┆              ┆              ┆ colonies and │
│            ┆         ┆ it?           ┆ colonies.    ┆              ┆              ┆ US           │
│            ┆         ┆               ┆ France has   ┆              ┆              ┆ involvement  │
│            ┆         ┆               ┆ intervened   ┆              ┆              ┆ in Latin     │
│            ┆         ┆               ┆ militarily   ┆              ┆              ┆ America,     │
│            ┆         ┆               ┆ in these     ┆              ┆              ┆ which is a   │
│            ┆         ┆               ┆ countries    ┆              ┆              ┆ broader      │
│            ┆         ┆               ┆ multiple     ┆              ┆              ┆ ideological  │
│            ┆         ┆               ┆ times, and   ┆              ┆              ┆ discussion   │
│            ┆         ┆               ┆ has close    ┆              ┆              ┆ not directly │
│            ┆         ┆               ┆ economic     ┆              ┆              ┆ tied to the  │
│            ┆         ┆               ┆ ties with    ┆              ┆              ┆ Gaza         │
│            ┆         ┆               ┆ these        ┆              ┆              ┆ conflict.    │
│            ┆         ┆               ┆ countries.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Many say the ┆              ┆              ┆              │
│            ┆         ┆               ┆ CFA franc    ┆              ┆              ┆              │
│            ┆         ┆               ┆ grants       ┆              ┆              ┆              │
│            ┆         ┆               ┆ France tight ┆              ┆              ┆              │
│            ┆         ┆               ┆ economic     ┆              ┆              ┆              │
│            ┆         ┆               ┆ control over ┆              ┆              ┆              │
│            ┆         ┆               ┆ these        ┆              ┆              ┆              │
│            ┆         ┆               ┆ countries    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and heavily  ┆              ┆              ┆              │
│            ┆         ┆               ┆ disadvantage ┆              ┆              ┆              │
│            ┆         ┆               ┆ s them. In   ┆              ┆              ┆              │
│            ┆         ┆               ┆ recent years ┆              ┆              ┆              │
│            ┆         ┆               ┆ rising       ┆              ┆              ┆              │
│            ┆         ┆               ┆ anti-French  ┆              ┆              ┆              │
│            ┆         ┆               ┆ sentiment    ┆              ┆              ┆              │
│            ┆         ┆               ┆ has          ┆              ┆              ┆              │
│            ┆         ┆               ┆ coincided    ┆              ┆              ┆              │
│            ┆         ┆               ┆ with the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ entry of     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Russian      ┆              ┆              ┆              │
│            ┆         ┆               ┆ forces into  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Francafrique ┆              ┆              ┆              │
│            ┆         ┆               ┆ . Do you     ┆              ┆              ┆              │
│            ┆         ┆               ┆ think        ┆              ┆              ┆              │
│            ┆         ┆               ┆ Francafrique ┆              ┆              ┆              │
│            ┆         ┆               ┆ is real and  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the reason   ┆              ┆              ┆              │
│            ┆         ┆               ┆ why these    ┆              ┆              ┆              │
│            ┆         ┆               ┆ countries    ┆              ┆              ┆              │
│            ┆         ┆               ┆ turned to    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Russia, or   ┆              ┆              ┆              │
│            ┆         ┆               ┆ is it an     ┆              ┆              ┆              │
│            ┆         ┆               ┆ anti-Western ┆              ┆              ┆              │
│            ┆         ┆               ┆ conspiracy   ┆              ┆              ┆              │
│            ┆         ┆               ┆ theory       ┆              ┆              ┆              │
│            ┆         ┆               ┆ peddled by   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Russia and   ┆              ┆              ┆              │
│            ┆         ┆               ┆ other        ┆              ┆              ┆              │
│            ┆         ┆               ┆ actors?      ┆              ┆              ┆              │
│ mv5drrq    ┆ 1kzgyse ┆ The Gaza      ┆ A hallmark   ┆ At some      ┆ 1            ┆ The comment  │
│            ┆         ┆ Genocide      ┆ of genocide  ┆ point in     ┆              ┆ dismisses    │
│            ┆         ┆ Consensus     ┆ throughout   ┆ time most of ┆              ┆ the validity │
│            ┆         ┆               ┆ history is   ┆ the reports  ┆              ┆ of reports   │
│            ┆         ┆               ┆ the          ┆ pointed out  ┆              ┆ regarding    │
│            ┆         ┆               ┆ widespread   ┆ that the     ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ hesitation   ┆ earth is     ┆              ┆ conflict by  │
│            ┆         ┆               ┆ to name it   ┆ flat, and    ┆              ┆ comparing    │
│            ┆         ┆               ┆ while it is  ┆ despite that ┆              ┆ them to a    │
│            ┆         ┆               ┆ still        ┆ it was       ┆              ┆ false        │
│            ┆         ┆               ┆ unfolding.   ┆ round. If    ┆              ┆ consensus    │
│            ┆         ┆               ┆ The          ┆ you believe  ┆              ┆ about the    │
│            ┆         ┆               ┆ perpetrators ┆ the earth is ┆              ┆ shape of the │
│            ┆         ┆               ┆ and those    ┆ flat please  ┆              ┆ Earth,       │
│            ┆         ┆               ┆ aligned have ┆ just revert  ┆              ┆ indicating a │
│            ┆         ┆               ┆ clear        ┆ the argument ┆              ┆ rejection of │
│            ┆         ┆               ┆ incentives   ┆ cause my     ┆              ┆ the          │
│            ┆         ┆               ┆ to deny      ┆ point        ┆              ┆ established  │
│            ┆         ┆               ┆ genocidal    ┆ remains the  ┆              ┆ narratives   │
│            ┆         ┆               ┆ intent and   ┆ same either  ┆              ┆ about the    │
│            ┆         ┆               ┆ actions,     ┆ way. Having  ┆              ┆ situation in │
│            ┆         ┆               ┆ even in the  ┆ a consensus  ┆              ┆ Gaza. This   │
│            ┆         ┆               ┆ face of      ┆ and multiple ┆              ┆ reflects a   │
│            ┆         ┆               ┆ mounting     ┆ reports that ┆              ┆ broader      │
│            ┆         ┆               ┆ evidence.    ┆ are based of ┆              ┆ ideological  │
│            ┆         ┆               ┆ This denial  ┆ one another  ┆              ┆ stance       │
│            ┆         ┆               ┆ serves not   ┆ doesnt make  ┆              ┆ rather than  │
│            ┆         ┆               ┆ only to      ┆ something    ┆              ┆ a direct     │
│            ┆         ┆               ┆ shield them  ┆ true. The    ┆              ┆ engagement   │
│            ┆         ┆               ┆ from legal   ┆ truth is not ┆              ┆ with the     │
│            ┆         ┆               ┆ consequences ┆ a result of  ┆              ┆ specifics of │
│            ┆         ┆               ┆ but also to  ┆ a democratic ┆              ┆ the          │
│            ┆         ┆               ┆ preserve a   ┆ voice.       ┆              ┆ conflict.    │
│            ┆         ┆               ┆ collective   ┆              ┆              ┆              │
│            ┆         ┆               ┆ identity,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ protect      ┆              ┆              ┆              │
│            ┆         ┆               ┆ moral        ┆              ┆              ┆              │
│            ┆         ┆               ┆ self-image,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and maintain ┆              ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 2

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ ms4k3vq    ┆ 1klpg3q ┆ Trump is      ┆ I mean obvs  ┆ If thats     ┆ 2            ┆ The comment  │
│            ┆         ┆ gonna free    ┆ this is the  ┆ what it      ┆              ┆ primarily    │
│            ┆         ┆ Palestine cuz ┆ Hottest of   ┆ take, im for ┆              ┆ discusses    │
│            ┆         ┆ the Qataris   ┆ hot takes    ┆ it lol       ┆              ┆ Trump's      │
│            ┆         ┆ gave him a    ┆ but also     ┆              ┆              ┆ potential    │
│            ┆         ┆ pretty shiny  ┆ maybe not?   ┆              ┆              ┆ actions      │
│            ┆         ┆ airplane      ┆ Like he      ┆              ┆              ┆ regarding    │
│            ┆         ┆               ┆ doesn’t care ┆              ┆              ┆ Palestine    │
│            ┆         ┆               ┆ about Israel ┆              ┆              ┆ and his      │
│            ┆         ┆               ┆ or Palestine ┆              ┆              ┆ motivations, │
│            ┆         ┆               ┆ or Jews or   ┆              ┆              ┆ which are    │
│            ┆         ┆               ┆ Arabs or     ┆              ┆              ┆ more focused │
│            ┆         ┆               ┆ anybody but  ┆              ┆              ┆ on US        │
│            ┆         ┆               ┆ himself and  ┆              ┆              ┆ politics and │
│            ┆         ┆               ┆ his wealth.  ┆              ┆              ┆ personal     │
│            ┆         ┆               ┆ So I can     ┆              ┆              ┆ gain rather  │
│            ┆         ┆               ┆ actually see ┆              ┆              ┆ than the     │
│            ┆         ┆               ┆ a world      ┆              ┆              ┆ core         │
│            ┆         ┆               ┆ where the    ┆              ┆              ┆ conflict     │
│            ┆         ┆               ┆ saudis and   ┆              ┆              ┆ itself. This │
│            ┆         ┆               ┆ Qataris and  ┆              ┆              ┆ makes it     │
│            ┆         ┆               ┆ Emiratis     ┆              ┆              ┆ less         │
│            ┆         ┆               ┆ flatter him  ┆              ┆              ┆ relevant to  │
│            ┆         ┆               ┆ so much that ┆              ┆              ┆ the actual   │
│            ┆         ┆               ┆ he continues ┆              ┆              ┆ situation in │
│            ┆         ┆               ┆ to sideline  ┆              ┆              ┆ Gaza.        │
│            ┆         ┆               ┆ Bibi and his ┆              ┆              ┆              │
│            ┆         ┆               ┆ right wing   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Zionist      ┆              ┆              ┆              │
│            ┆         ┆               ┆ thugs and    ┆              ┆              ┆              │
│            ┆         ┆               ┆ eventually   ┆              ┆              ┆              │
│            ┆         ┆               ┆ decides to   ┆              ┆              ┆              │
│            ┆         ┆               ┆ rebuild      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Palestine    ┆              ┆              ┆              │
│            ┆         ┆               ┆ for          ┆              ┆              ┆              │
│            ┆         ┆               ┆ Palestinians ┆              ┆              ┆              │
│            ┆         ┆               ┆ because it   ┆              ┆              ┆              │
│            ┆         ┆               ┆ will piss    ┆              ┆              ┆              │
│            ┆         ┆               ┆ off people   ┆              ┆              ┆              │
│            ┆         ┆               ┆ he hates and ┆              ┆              ┆              │
│            ┆         ┆               ┆ give him a   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Nobel peace  ┆              ┆              ┆              │
│            ┆         ┆               ┆ prize which  ┆              ┆              ┆              │
│            ┆         ┆               ┆ he covets    ┆              ┆              ┆              │
│            ┆         ┆               ┆ since Obama  ┆              ┆              ┆              │
│            ┆         ┆               ┆ got one for  ┆              ┆              ┆              │
│            ┆         ┆               ┆ basically    ┆              ┆              ┆              │
│            ┆         ┆               ┆ doing jack   ┆              ┆              ┆              │
│            ┆         ┆               ┆ all.         ┆              ┆              ┆              │
│ mrrx4la    ┆ 1kk56ys ┆ How does this ┆ I just read  ┆ He’s such a  ┆ 2            ┆ The comment  │
│            ┆         ┆ not put all   ┆ Trump is     ┆ fool.  You   ┆              ┆ primarily    │
│            ┆         ┆ Jews in more  ┆ taking a     ┆ know it’s    ┆              ┆ focuses on   │
│            ┆         ┆ danger?       ┆ (bribe) new  ┆ filled with  ┆              ┆ US politics  │
│            ┆         ┆               ┆ AirForce 1   ┆ surveillance ┆              ┆ and a        │
│            ┆         ┆               ┆ jet gifted   ┆ and totally  ┆              ┆ specific     │
│            ┆         ┆               ┆ from Qatar.  ┆ compromised  ┆              ┆ individual   │
│            ┆         ┆               ┆ I feel like  ┆ National     ┆              ┆ (Trump),     │
│            ┆         ┆               ┆ any progress ┆ security     ┆              ┆ rather than  │
│            ┆         ┆               ┆ he may have  ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ made for     ┆              ┆              ┆ addressing   │
│            ┆         ┆               ┆ Jews (I’m    ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ not a        ┆              ┆              ┆ conflict or  │
│            ┆         ┆               ┆ Trumper!)    ┆              ┆              ┆ its          │
│            ┆         ┆               ┆ has been     ┆              ┆              ┆ implications │
│            ┆         ┆               ┆ erased with  ┆              ┆              ┆ for Jews and │
│            ┆         ┆               ┆ one truly    ┆              ┆              ┆ Israel.      │
│            ┆         ┆               ┆ unnecessary  ┆              ┆              ┆ While it     │
│            ┆         ┆               ┆ decision     ┆              ┆              ┆ touches on   │
│            ┆         ┆               ┆ which is a   ┆              ┆              ┆ concerns for │
│            ┆         ┆               ┆ huge symbol  ┆              ┆              ┆ Jewish       │
│            ┆         ┆               ┆ (bribe). It  ┆              ┆              ┆ safety, it   │
│            ┆         ┆               ┆ makes me     ┆              ┆              ┆ does so in a │
│            ┆         ┆               ┆ think Jews   ┆              ┆              ┆ way that is  │
│            ┆         ┆               ┆ and Israel   ┆              ┆              ┆ more about   │
│            ┆         ┆               ┆ are in the   ┆              ┆              ┆ domestic     │
│            ┆         ┆               ┆ greatest     ┆              ┆              ┆ political    │
│            ┆         ┆               ┆ danger since ┆              ┆              ┆ commentary   │
│            ┆         ┆               ┆ 10/7. What   ┆              ┆              ┆ than the     │
│            ┆         ┆               ┆ is he        ┆              ┆              ┆ core         │
│            ┆         ┆               ┆ doing?!      ┆              ┆              ┆ conflict     │
│            ┆         ┆               ┆              ┆              ┆              ┆ itself.      │
│ nm1o9xi    ┆ 1ojbcnz ┆ 35 child got  ┆ Sources:     ┆ #            ┆ 2            ┆ The comment  │
│            ┆         ┆ killed during ┆ https://www. ┆ #            ┆              ┆ primarily    │
│            ┆         ┆ the ceasefire ┆ aljazeera.co ┆ Help         ┆              ┆ focuses on   │
│            ┆         ┆ Overnight by  ┆ m/video/news ┆ Palestinians ┆              ┆ promoting    │
│            ┆         ┆ strikes       ┆ feed/2025/10 ┆ in need      ┆              ┆ humanitarian │
│            ┆         ┆               ┆ /29/israel-k ┆ today. Your  ┆              ┆ aid for      │
│            ┆         ┆               ┆ ills-over-10 ┆ donation     ┆              ┆ Palestinians │
│            ┆         ┆               ┆ 0-palestinia ┆ delivers     ┆              ┆ and includes │
│            ┆         ┆               ┆ ns-in-new-st ┆ life-saving  ┆              ┆ links to     │
│            ┆         ┆               ┆ rikes-on-gaz ┆ food,        ┆              ┆ donation     │
│            ┆         ┆               ┆ a            ┆ medical, and ┆              ┆ resources,   │
│            ┆         ┆               ┆              ┆ humanitarian ┆              ┆ which, while │
│            ┆         ┆               ┆ https://reli ┆ aid to       ┆              ┆ related to   │
│            ┆         ┆               ┆ efweb.int/re ┆ families who ┆              ┆ the          │
│            ┆         ┆               ┆ port/occupie ┆ are          ┆              ┆ humanitarian │
│            ┆         ┆               ┆ d-palestinia ┆ struggling.  ┆              ┆ aspect of    │
│            ┆         ┆               ┆ n-territory/ ┆ [Give now    ┆              ┆ the          │
│            ┆         ┆               ┆ news-quote-r ┆ and bring    ┆              ┆ conflict,    │
│            ┆         ┆               ┆ eports-35-ch ┆ hope to      ┆              ┆ does not     │
│            ┆         ┆               ┆ ildren-among ┆ those in cri ┆              ┆ directly     │
│            ┆         ┆               ┆ -those-kille ┆ sis](https:/ ┆              ┆ discuss the  │
│            ┆         ┆               ┆ d-renewed-ai ┆ /www.reddit. ┆              ┆ core events  │
│            ┆         ┆               ┆ rstrikes-isr ┆ com/r/Palest ┆              ┆ or           │
│            ┆         ┆               ┆ aeli-forces- ┆ ine/wiki/don ┆              ┆ implications │
│            ┆         ┆               ┆ gaza         ┆ ate/).       ┆              ┆ of the Gaza  │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict     │
│            ┆         ┆               ┆              ┆ [Join our    ┆              ┆ itself.      │
│            ┆         ┆               ┆              ┆ official     ┆              ┆              │
│            ┆         ┆               ┆              ┆ discord serv ┆              ┆              │
│            ┆         ┆               ┆              ┆ er!](https:/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ /discord.gg/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ rpalestine), ┆              ┆              │
│            ┆         ┆               ┆              ┆ and visit    ┆              ┆              │
│            ┆         ┆               ┆              ┆ our          ┆              ┆              │
│            ┆         ┆               ┆              ┆ [Palestine   ┆              ┆              │
│            ┆         ┆               ┆              ┆ Twitter Comm ┆              ┆              │
│            ┆         ┆               ┆              ┆ unity](https ┆              ┆              │
│            ┆         ┆               ┆              ┆ ://twitter.c ┆              ┆              │
│            ┆         ┆               ┆              ┆ om/i/communi ┆              ┆              │
│            ┆         ┆               ┆              ┆ ties/1504131 ┆              ┆              │
│            ┆         ┆               ┆              ┆ 282137239555 ┆              ┆              │
│            ┆         ┆               ┆              ┆ ).           ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆ This is a    ┆              ┆              │
│            ┆         ┆               ┆              ┆ heavily      ┆              ┆              │
│            ┆         ┆               ┆              ┆ moderated    ┆              ┆              │
│            ┆         ┆               ┆              ┆ subreddit.   ┆              ┆              │
│            ┆         ┆               ┆              ┆ **Please     ┆              ┆              │
│            ┆         ┆               ┆              ┆ read the [ru ┆              ┆              │
│            ┆         ┆               ┆              ┆ les](https:/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ /www.reddit. ┆              ┆              │
│            ┆         ┆               ┆              ┆ com/r/Palest ┆              ┆              │
│            ┆         ┆               ┆              ┆ ine/wiki/rul ┆              ┆              │
│            ┆         ┆               ┆              ┆ es/)**, and  ┆              ┆              │
│            ┆         ┆               ┆              ┆ report any   ┆              ┆              │
│            ┆         ┆               ┆              ┆ post or      ┆              ┆              │
│            ┆         ┆               ┆              ┆ comment      ┆              ┆              │
│            ┆         ┆               ┆              ┆ displaying:  ┆              ┆              │
│            ┆         ┆               ┆              ┆ Zionist      ┆              ┆              │
│            ┆         ┆               ┆              ┆ propaganda   ┆              ┆              │
│            ┆         ┆               ┆              ┆ hasbara,     ┆              ┆              │
│            ┆         ┆               ┆              ┆ bigotry,     ┆              ┆              │
│            ┆         ┆               ┆              ┆ hate speech, ┆              ┆              │
│            ┆         ┆               ┆              ┆ genocide     ┆              ┆              │
│            ┆         ┆               ┆              ┆ denial, Isla ┆              ┆              │
│            ┆         ┆               ┆              ┆ mophobia,    ┆              ┆              │
│            ┆         ┆               ┆              ┆ trolling,    ┆              ┆              │
│            ┆         ┆               ┆              ┆ etc.         ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆ >!(Thanks    ┆              ┆              │
│            ┆         ┆               ┆              ┆ for posting, ┆              ┆              │
│            ┆         ┆               ┆              ┆ u/ibrahim_D1 ┆              ┆              │
│            ┆         ┆               ┆              ┆ 2!)!<        ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆ *I am a bot, ┆              ┆              │
│            ┆         ┆               ┆              ┆ and this     ┆              ┆              │
│            ┆         ┆               ┆              ┆ action was   ┆              ┆              │
│            ┆         ┆               ┆              ┆ performed    ┆              ┆              │
│            ┆         ┆               ┆              ┆ automaticall ┆              ┆              │
│            ┆         ┆               ┆              ┆ y. Please    ┆              ┆              │
│            ┆         ┆               ┆              ┆ [contact the ┆              ┆              │
│            ┆         ┆               ┆              ┆ moderators   ┆              ┆              │
│            ┆         ┆               ┆              ┆ of this subr ┆              ┆              │
│            ┆         ┆               ┆              ┆ eddit](/mess ┆              ┆              │
│            ┆         ┆               ┆              ┆ age/compose/ ┆              ┆              │
│            ┆         ┆               ┆              ┆ ?to=/r/Pales ┆              ┆              │
│            ┆         ┆               ┆              ┆ tine) if you ┆              ┆              │
│            ┆         ┆               ┆              ┆ have any     ┆              ┆              │
│            ┆         ┆               ┆              ┆ questions or ┆              ┆              │
│            ┆         ┆               ┆              ┆ concerns.*   ┆              ┆              │
│ o8krbtz    ┆ 1rkiv36 ┆ Army Guilt    ┆ I was in the ┆ **Note from  ┆ 2            ┆ The comment  │
│            ┆         ┆ and Fomo      ┆ air defence  ┆ the mods**:  ┆              ┆ reflects     │
│            ┆         ┆               ┆ as a         ┆ During this  ┆              ┆ personal     │
│            ┆         ┆               ┆ volunteer    ┆ time, many   ┆              ┆ feelings of  │
│            ┆         ┆               ┆ lone         ┆ posts and    ┆              ┆ guilt and    │
│            ┆         ┆               ┆ soldier,     ┆ comments are ┆              ┆ FOMO related │
│            ┆         ┆               ┆ already had  ┆ held for     ┆              ┆ to military  │
│            ┆         ┆               ┆ a war with   ┆ review       ┆              ┆ service, but │
│            ┆         ┆               ┆ Iran, yet    ┆ before       ┆              ┆ it does not  │
│            ┆         ┆               ┆ feel a lot   ┆ appearing on ┆              ┆ directly     │
│            ┆         ┆               ┆ of fomo and  ┆ the site.    ┆              ┆ address the  │
│            ┆         ┆               ┆ guilt for    ┆ This is      ┆              ┆ Gaza         │
│            ┆         ┆               ┆ not being    ┆ intentional. ┆              ┆ conflict or  │
│            ┆         ┆               ┆ with my guys ┆ Please allow ┆              ┆ its implicat │
│            ┆         ┆               ┆ now, I’m not ┆ your human   ┆              ┆ ions, making │
│            ┆         ┆               ┆ even in      ┆ mods some    ┆              ┆ it more of a │
│            ┆         ┆               ┆ Israel. I    ┆ time to      ┆              ┆ personal     │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 3

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ ngpu9mq    ┆ 1nsbe93 ┆ Professors at ┆ I had to run ┆ They mean    ┆ 3            ┆ The comment  │
│            ┆         ┆ Coimbra       ┆ away from    ┆ Jewish       ┆              ┆ refers to    │
│            ┆         ┆ University    ┆ Portugal     ┆ student, no  ┆              ┆ the          │
│            ┆         ┆ are calling   ┆ after it     ┆ doubt.       ┆              ┆ targeting of │
│            ┆         ┆ to kill       ┆ turned into  ┆              ┆              ┆ Jewish       │
│            ┆         ┆ Israeli       ┆ a lawless    ┆              ┆              ┆ students and │
│            ┆         ┆ students      ┆ land. Europe ┆              ┆              ┆ the          │
│            ┆         ┆               ┆ is gone...   ┆              ┆              ┆ atmosphere   │
│            ┆         ┆               ┆              ┆              ┆              ┆ of hostility │
│            ┆         ┆               ┆ That's after ┆              ┆              ┆ towards      │
│            ┆         ┆               ┆ our work in  ┆              ┆              ┆ them, which  │
│            ┆         ┆               ┆ the press:   ┆              ┆              ┆ relates to   │
│            ┆         ┆               ┆ https://www. ┆              ┆              ┆ the broader  │
│            ┆         ┆               ┆ reddit.com/r ┆              ┆              ┆ context of   │
│            ┆         ┆               ┆ /Jewish/s/uj ┆              ┆              ┆ antisemitism │
│            ┆         ┆               ┆ G3cfXZPW     ┆              ┆              ┆ and violence │
│            ┆         ┆               ┆              ┆              ┆              ┆ associated   │
│            ┆         ┆               ┆ Justice      ┆              ┆              ┆ with the     │
│            ┆         ┆               ┆ system does  ┆              ┆              ┆ Gaza         │
│            ┆         ┆               ┆ not work,    ┆              ┆              ┆ conflict.    │
│            ┆         ┆               ┆ university   ┆              ┆              ┆ However, it  │
│            ┆         ┆               ┆ did not care ┆              ┆              ┆ does not     │
│            ┆         ┆               ┆ about calls  ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ from the     ┆              ┆              ┆ discuss the  │
│            ┆         ┆               ┆ American,    ┆              ┆              ┆ core         │
│            ┆         ┆               ┆ Brazilian,   ┆              ┆              ┆ conflict     │
│            ┆         ┆               ┆ German or    ┆              ┆              ┆ itself or    │
│            ┆         ┆               ┆ Israeli      ┆              ┆              ┆ the          │
│            ┆         ┆               ┆ embassies    ┆              ┆              ┆ situation in │
│            ┆         ┆               ┆ after Jews   ┆              ┆              ┆ Gaza.        │
│            ┆         ┆               ┆ from         ┆              ┆              ┆              │
│            ┆         ┆               ┆ multiple     ┆              ┆              ┆              │
│            ┆         ┆               ┆ countries    ┆              ┆              ┆              │
│            ┆         ┆               ┆ had to       ┆              ┆              ┆              │
│            ┆         ┆               ┆ escape. The  ┆              ┆              ┆              │
│            ┆         ┆               ┆ press did    ┆              ┆              ┆              │
│            ┆         ┆               ┆ not affect   ┆              ┆              ┆              │
│            ┆         ┆               ┆ them.        ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Seems like   ┆              ┆              ┆              │
│            ┆         ┆               ┆ we're back   ┆              ┆              ┆              │
│            ┆         ┆               ┆ in Nazi      ┆              ┆              ┆              │
│            ┆         ┆               ┆ times.       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Edit:        ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ For those    ┆              ┆              ┆              │
│            ┆         ┆               ┆ who asked, I ┆              ┆              ┆              │
│            ┆         ┆               ┆ know who     ┆              ┆              ┆              │
│            ┆         ┆               ┆ they are.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ 1. Yes they  ┆              ┆              ┆              │
│            ┆         ┆               ┆ are          ┆              ┆              ┆              │
│            ┆         ┆               ┆ professors   ┆              ┆              ┆              │
│            ┆         ┆               ┆ (The major   ┆              ┆              ┆              │
│            ┆         ┆               ┆ one is named ┆              ┆              ┆              │
│            ┆         ┆               ┆ at the CAM   ┆              ┆              ┆              │
│            ┆         ┆               ┆ article, htt ┆              ┆              ┆              │
│            ┆         ┆               ┆ ps://combata ┆              ┆              ┆              │
│            ┆         ┆               ┆ ntisemitism. ┆              ┆              ┆              │
│            ┆         ┆               ┆ org/cam-news ┆              ┆              ┆              │
│            ┆         ┆               ┆ /one-student ┆              ┆              ┆              │
│            ┆         ┆               ┆ s-fight-agai ┆              ┆              ┆              │
│            ┆         ┆               ┆ nst-antisemi ┆              ┆              ┆              │
│            ┆         ┆               ┆ tism-in-port ┆              ┆              ┆              │
│            ┆         ┆               ┆ ugal/ , I've ┆              ┆              ┆              │
│            ┆         ┆               ┆ actually     ┆              ┆              ┆              │
│            ┆         ┆               ┆ taken this   ┆              ┆              ┆              │
│            ┆         ┆               ┆ picture from ┆              ┆              ┆              │
│            ┆         ┆               ┆ her own      ┆              ┆              ┆              │
│            ┆         ┆               ┆ Instagram    ┆              ┆              ┆              │
│            ┆         ┆               ┆ account -    ┆              ┆              ┆              │
│            ┆         ┆               ┆ she's behind ┆              ┆              ┆              │
│            ┆         ┆               ┆ as_sentadas) ┆              ┆              ┆              │
│            ┆         ┆               ┆ . There's    ┆              ┆              ┆              │
│            ┆         ┆               ┆ also plenty  ┆              ┆              ┆              │
│            ┆         ┆               ┆ of students  ┆              ┆              ┆              │
│            ┆         ┆               ┆ but when     ┆              ┆              ┆              │
│            ┆         ┆               ┆ it's paid    ┆              ┆              ┆              │
│            ┆         ┆               ┆ faculty it's ┆              ┆              ┆              │
│            ┆         ┆               ┆ even more    ┆              ┆              ┆              │
│            ┆         ┆               ┆ disgusting.  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ 2. Yes they  ┆              ┆              ┆              │
│            ┆         ┆               ┆ call to      ┆              ┆              ┆              │
│            ┆         ┆               ┆ murder, they ┆              ┆              ┆              │
│            ┆         ┆               ┆ frequently   ┆              ┆              ┆              │
│            ┆         ┆               ┆ chant for    ┆              ┆              ┆              │
│            ┆         ┆               ┆ intifada,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ put pictures ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Yahya     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Sinwar all   ┆              ┆              ┆              │
│            ┆         ┆               ┆ over campus, ┆              ┆              ┆              │
│            ┆         ┆               ┆ and sell     ┆              ┆              ┆              │
│            ┆         ┆               ┆ stickers     ┆              ┆              ┆              │
│            ┆         ┆               ┆ claiming     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israelis do  ┆              ┆              ┆              │
│            ┆         ┆               ┆ not have a   ┆              ┆              ┆              │
│            ┆         ┆               ┆ right to     ┆              ┆              ┆              │
│            ┆         ┆               ┆ live in the  ┆              ┆              ┆              │
│            ┆         ┆               ┆ world - …    ┆              ┆              ┆              │
│ ob3r2hj    ┆ 1rwkccm ┆ Joseph Kent,  ┆              ┆ We don't     ┆ 3            ┆ The comment  │
│            ┆         ┆ who resigned  ┆              ┆ have the     ┆              ┆ discusses    │
│            ┆         ┆ today from    ┆              ┆ privilege of ┆              ┆ the          │
│            ┆         ┆ his role as   ┆              ┆ ending this  ┆              ┆ implications │
│            ┆         ┆ Director of   ┆              ┆ war soon. If ┆              ┆ of the       │
│            ┆         ┆ Counterterror ┆              ┆ we do, not   ┆              ┆ ongoing war  │
│            ┆         ┆ ism Center    ┆              ┆ only will    ┆              ┆ and its      │
│            ┆         ┆ (US),         ┆              ┆ Iran         ┆              ┆ impact on    │
│            ┆         ┆ believes that ┆              ┆ recover, but ┆              ┆ regional     │
│            ┆         ┆ Israel        ┆              ┆ it will      ┆              ┆ stability,   │
│            ┆         ┆ manufactured  ┆              ┆ destroy our  ┆              ┆ particularly │
│            ┆         ┆ the Syrian    ┆              ┆ credibility  ┆              ┆ regarding    │
│            ┆         ┆ Civil War and ┆              ┆ and leave an ┆              ┆ Iran, which  │
│            ┆         ┆ the spreading ┆              ┆ entire       ┆              ┆ is           │
│            ┆         ┆ of ISIS       ┆              ┆ generation   ┆              ┆ indirectly   │
│            ┆         ┆               ┆              ┆ radicalized  ┆              ┆ related to   │
│            ┆         ┆               ┆              ┆ against us.  ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict but │
│            ┆         ┆               ┆              ┆ This war     ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ must end     ┆              ┆ focus on the │
│            ┆         ┆               ┆              ┆ with a free  ┆              ┆ core issues  │
│            ┆         ┆               ┆              ┆ Iran, and a  ┆              ┆ of the       │
│            ┆         ┆               ┆              ┆ peace deal   ┆              ┆ conflict     │
│            ┆         ┆               ┆              ┆ on the white ┆              ┆ itself.      │
│            ┆         ┆               ┆              ┆ house lawn.  ┆              ┆              │
│ mz2t17i    ┆ 1lhaiqa ┆ Megathread:   ┆ At 7:50 p.m. ┆ THE ANTI-WAR ┆ 3            ┆ The comment  │
│            ┆         ┆ US President  ┆ US Eastern,  ┆ PRESIDENT    ┆              ┆ sarcasticall │
│            ┆         ┆ Trump Says    ┆ US President ┆ EVERYBODY.   ┆              ┆ y critiques  │
│            ┆         ┆ That The US   ┆ Donald Trump ┆              ┆              ┆ the actions  │
│            ┆         ┆ Military Has  ┆ posted on    ┆ IN ONLY 6    ┆              ┆ of the US    │
│            ┆         ┆ Bombed        ┆ Truth Social ┆ FUCKING      ┆              ┆ President    │
│            ┆         ┆ Multiple      ┆ "We have     ┆ MONTHS.      ┆              ┆ regarding    │
│            ┆         ┆ Iranian       ┆ completed    ┆              ┆              ┆ military     │
│            ┆         ┆ Nuclear Sites ┆ our very     ┆              ┆              ┆ strikes,     │
│            ┆         ┆               ┆ successful   ┆              ┆              ┆ which        │
│            ┆         ┆               ┆ attack on    ┆              ┆              ┆ indirectly   │
│            ┆         ┆               ┆ the three    ┆              ┆              ┆ relates to   │
│            ┆         ┆               ┆ Nuclear      ┆              ┆              ┆ public       │
│            ┆         ┆               ┆ sites in     ┆              ┆              ┆ opinion on   │
│            ┆         ┆               ┆ Iran,        ┆              ┆              ┆ military     │
│            ┆         ┆               ┆ including    ┆              ┆              ┆ involvement  │
│            ┆         ┆               ┆ Fordow,      ┆              ┆              ┆ in the Gaza  │
│            ┆         ┆               ┆ Natanz, and  ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆ Esfahan. All ┆              ┆              ┆ broader      │
│            ┆         ┆               ┆ planes are   ┆              ┆              ┆ Middle       │
│            ┆         ┆               ┆ now outside  ┆              ┆              ┆ Eastern      │
│            ┆         ┆               ┆ of Iran air  ┆              ┆              ┆ tensions.    │
│            ┆         ┆               ┆ space. A     ┆              ┆              ┆              │
│            ┆         ┆               ┆ full payload ┆              ┆              ┆              │
│            ┆         ┆               ┆ of BOMBS was ┆              ┆              ┆              │
│            ┆         ┆               ┆ dropped on   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the primary  ┆              ┆              ┆              │
│            ┆         ┆               ┆ site,        ┆              ┆              ┆              │
│            ┆         ┆               ┆ Fordow. All  ┆              ┆              ┆              │
│            ┆         ┆               ┆ planes are   ┆              ┆              ┆              │
│            ┆         ┆               ┆ safely on    ┆              ┆              ┆              │
│            ┆         ┆               ┆ their way    ┆              ┆              ┆              │
│            ┆         ┆               ┆ home. Congra ┆              ┆              ┆              │
│            ┆         ┆               ┆ tulations to ┆              ┆              ┆              │
│            ┆         ┆               ┆ our great    ┆              ┆              ┆              │
│            ┆         ┆               ┆ American     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Warriors.    ┆              ┆              ┆              │
│            ┆         ┆               ┆ There is not ┆              ┆              ┆              │
│            ┆         ┆               ┆ another      ┆              ┆              ┆              │
│            ┆         ┆               ┆ military in  ┆              ┆              ┆              │
│            ┆         ┆               ┆ the World    ┆              ┆              ┆              │
│            ┆         ┆               ┆ that could   ┆              ┆              ┆              │
│            ┆         ┆               ┆ have done    ┆              ┆              ┆              │
│            ┆         ┆               ┆ this. NOW IS ┆              ┆              ┆              │
│            ┆         ┆               ┆ THE TIME FOR ┆              ┆              ┆              │
│            ┆         ┆               ┆ PEACE! Thank ┆              ┆              ┆              │
│            ┆         ┆               ┆ you for your ┆              ┆              ┆              │
│            ┆         ┆               ┆ attention to ┆              ┆              ┆              │
│            ┆         ┆               ┆ this         ┆              ┆              ┆              │
│            ┆         ┆               ┆ matter".     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ [The AP's    ┆              ┆              ┆              │
│            ┆         ┆               ┆ live updates ┆              ┆              ┆              │
│            ┆         ┆               ┆ page can be  ┆              ┆              ┆              │
│            ┆         ┆               ┆ found here]( ┆              ┆              ┆              │
│            ┆         ┆               ┆ https://apne ┆              ┆              ┆              │
│            ┆         ┆               ┆ ws.com/live/ ┆              ┆              ┆              │
│            ┆         ┆               ┆ israel-iran- ┆              ┆              ┆              │
│            ┆         ┆               ┆ war-updates) ┆              ┆              ┆              │
│            ┆         ┆               ┆ .            ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ ---          ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Trump is set ┆              ┆              ┆              │

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 4

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ nq2f00z    ┆ 1p35ool ┆ Sarah         ┆ [https://xca ┆ Honestly,    ┆ 4            ┆ The comment  │
│            ┆         ┆ Hurwitz,      ┆ ncel.com/Dro ┆ how would    ┆              ┆ critiques a  │
│            ┆         ┆ former Obama  ┆ pSiteNews/st ┆ you change   ┆              ┆ specific     │
│            ┆         ┆ speechwriter, ┆ atus/1991709 ┆ people like  ┆              ┆ viewpoint on │
│            ┆         ┆ says the Gaza ┆ 907179995401 ┆ this? They   ┆              ┆ the Gaza     │
│            ┆         ┆ genocide is   ┆ ](https://xc ┆ are either   ┆              ┆ conflict and │
│            ┆         ┆ imaginary &   ┆ ancel.com/Dr ┆ paid to say  ┆              ┆ discusses    │
│            ┆         ┆ antisemitic   ┆ opSiteNews/s ┆ this and are ┆              ┆ the          │
│            ┆         ┆ like claims   ┆ tatus/199170 ┆ doing some   ┆              ┆ conflation   │
│            ┆         ┆ of "white gen ┆ 990717999540 ┆ sick         ┆              ┆ of           │
│            ┆         ┆ ocide"/"repla ┆ 1)           ┆ calculation  ┆              ┆ anti-racism  │
│            ┆         ┆ cement        ┆              ┆ in their     ┆              ┆ with anti-Zi │
│            ┆         ┆ theory" in    ┆              ┆ heads of     ┆              ┆ onism, which │
│            ┆         ┆ the US.       ┆              ┆ using jewish ┆              ┆ relates to   │
│            ┆         ┆               ┆              ┆  people and  ┆              ┆ public       │
│            ┆         ┆               ┆              ┆ the identity ┆              ┆ opinion and  │
│            ┆         ┆               ┆              ┆ as a shield  ┆              ┆ discourse    │
│            ┆         ┆               ┆              ┆ to advance   ┆              ┆ surrounding  │
│            ┆         ┆               ┆              ┆ their goals  ┆              ┆ the          │
│            ┆         ┆               ┆              ┆ or just genu ┆              ┆ conflict.    │
│            ┆         ┆               ┆              ┆ inely        ┆              ┆ However, it  │
│            ┆         ┆               ┆              ┆ delusional   ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ to equate    ┆              ┆ directly     │
│            ┆         ┆               ┆              ┆ anti racism  ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ = anti       ┆              ┆ core events  │
│            ┆         ┆               ┆              ┆ zionism =    ┆              ┆ or           │
│            ┆         ┆               ┆              ┆ antisemitism ┆              ┆ humanitarian │
│            ┆         ┆               ┆              ┆ = facism...  ┆              ┆ aspects of   │
│            ┆         ┆               ┆              ┆ wtf.         ┆              ┆ the          │
│            ┆         ┆               ┆              ┆              ┆              ┆ situation.   │
│ nj9jdcw    ┆ 1o5hbv4 ┆ Israeli       ┆              ┆ They know    ┆ 4            ┆ The comment  │
│            ┆         ┆ opposition    ┆              ┆ that global  ┆              ┆ addresses    │
│            ┆         ┆ Leader Yair   ┆              ┆ public       ┆              ┆ the          │
│            ┆         ┆ Lapid: Those  ┆              ┆ opinion of   ┆              ┆ perception   │
│            ┆         ┆ who           ┆              ┆ them is      ┆              ┆ of global    │
│            ┆         ┆ demonstrated  ┆              ┆ totally      ┆              ┆ public       │
│            ┆         ┆ against       ┆              ┆ f*****       ┆              ┆ opinion      │
│            ┆         ┆ Israel in     ┆              ┆ they're      ┆              ┆ regarding    │
│            ┆         ┆ London, Rome, ┆              ┆ trying to do ┆              ┆ Israel's     │
│            ┆         ┆ Paris, and    ┆              ┆ damage       ┆              ┆ actions and  │
│            ┆         ┆ Columbia      ┆              ┆ control.     ┆              ┆ references   │
│            ┆         ┆ University    ┆              ┆ It won't     ┆              ┆ war crimes,  │
│            ┆         ┆ were deceived ┆              ┆ work, we     ┆              ┆ which are    │
│            ┆         ┆ by            ┆              ┆ have the     ┆              ┆ directly     │
│            ┆         ┆ propaganda.   ┆              ┆ videos and   ┆              ┆ related to   │
│            ┆         ┆ Now that the  ┆              ┆ pictures     ┆              ┆ the ongoing  │
│            ┆         ┆ war has       ┆              ┆ that their   ┆              ┆ Gaza         │
│            ┆         ┆ stopped,      ┆              ┆ own people   ┆              ┆ conflict and │
│            ┆         ┆ learn the     ┆              ┆ posted on    ┆              ┆ its implicat │
│            ┆         ┆ facts: there  ┆              ┆ their social ┆              ┆ ions.        │
│            ┆         ┆ was no        ┆              ┆ media        ┆              ┆              │
│            ┆         ┆ genocide, no  ┆              ┆ bragging     ┆              ┆              │
│            ┆         ┆ intentional   ┆              ┆ about their  ┆              ┆              │
│            ┆         ┆ starvation in ┆              ┆ war crimes.  ┆              ┆              │
│            ┆         ┆ Gaza.” They   ┆              ┆              ┆              ┆              │
│            ┆         ┆ really hope   ┆              ┆              ┆              ┆              │
│            ┆         ┆ that we will  ┆              ┆              ┆              ┆              │
│            ┆         ┆ forget        ┆              ┆              ┆              ┆              │
│ nm0epol    ┆ 1oj3axz ┆ Trump’s       ┆              ┆ More like    ┆ 4            ┆ The comment  │
│            ┆         ┆ unravelling   ┆              ┆ Israel       ┆              ┆ directly     │
│            ┆         ┆ Gaza truce    ┆              ┆ didn’t want  ┆              ┆ addresses    │
│            ┆         ┆ reveals a     ┆              ┆ it the hell  ┆              ┆ the actions  │
│            ┆         ┆ core truth –  ┆              ┆ are you on   ┆              ┆ of Israel    │
│            ┆         ┆ neither side  ┆              ┆ Israel keeps ┆              ┆ regarding    │
│            ┆         ┆ wanted it     ┆              ┆ breaking it! ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆              ┆              ┆ truce,       │
│            ┆         ┆               ┆              ┆              ┆              ┆ indicating a │
│            ┆         ┆               ┆              ┆              ┆              ┆ clear        │
│            ┆         ┆               ┆              ┆              ┆              ┆ opinion on   │
│            ┆         ┆               ┆              ┆              ┆              ┆ the conflict │
│            ┆         ┆               ┆              ┆              ┆              ┆ and its      │
│            ┆         ┆               ┆              ┆              ┆              ┆ dynamics,    │
│            ┆         ┆               ┆              ┆              ┆              ┆ which is     │
│            ┆         ┆               ┆              ┆              ┆              ┆ relevant to  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the ongoing  │
│            ┆         ┆               ┆              ┆              ┆              ┆ situation.   │
│ nff6j3r    ┆ 1nmngki ┆ If this is    ┆              ┆ Israel are   ┆ 4            ┆ The comment  │
│            ┆         ┆ the case then ┆              ┆ never asking ┆              ┆ implies a    │
│            ┆         ┆ you should    ┆              ┆ themselves   ┆              ┆ critique of  │
│            ┆         ┆ consider that ┆              ┆ this.        ┆              ┆ Israel's     │
│            ┆         ┆ maybe you are ┆              ┆              ┆              ┆ perspective  │
│            ┆         ┆ the problem   ┆              ┆ https://prev ┆              ┆ on the       │
│            ┆         ┆               ┆              ┆ iew.redd.it/ ┆              ┆ conflict,    │
│            ┆         ┆               ┆              ┆ k8jelyo90jqf ┆              ┆ which        │
│            ┆         ┆               ┆              ┆ 1.png?width= ┆              ┆ relates to   │
│            ┆         ┆               ┆              ┆ 711&format=p ┆              ┆ public       │
│            ┆         ┆               ┆              ┆ ng&auto=webp ┆              ┆ opinion and  │
│            ┆         ┆               ┆              ┆ &s=7c40928ea ┆              ┆ the actions  │
│            ┆         ┆               ┆              ┆ 12937ca96208 ┆              ┆ of one of    │
│            ┆         ┆               ┆              ┆ 58e70013eac2 ┆              ┆ the main     │
│            ┆         ┆               ┆              ┆ f0e4524      ┆              ┆ actors       │
│            ┆         ┆               ┆              ┆              ┆              ┆ involved in  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict.    │
│ mm4dd2b    ┆ 1jtig0l ┆ What happened ┆ I recall     ┆ From what    ┆ 4            ┆ The comment  │
│            ┆         ┆ to Gazan clan ┆ earlier in   ┆ I've         ┆              ┆ discusses    │
│            ┆         ┆ s/families to ┆ the war that ┆ gathered,    ┆              ┆ the          │
│            ┆         ┆ whom we       ┆ outlets      ┆ the clans    ┆              ┆ potential    │
│            ┆         ┆ contemplated  ┆ reported     ┆ don't have   ┆              ┆ role of      │
│            ┆         ┆ handing the   ┆ Israel’s     ┆ the kind of  ┆              ┆ Gazan clans  │
│            ┆         ┆ keys to Gaza? ┆ desire to    ┆ power to be  ┆              ┆ in the       │
│            ┆         ┆               ┆ hand         ┆ able to run  ┆              ┆ governance   │
│            ┆         ┆               ┆ everyday     ┆ it. They're  ┆              ┆ of Gaza and  │
│            ┆         ┆               ┆ operations   ┆ powerful in  ┆              ┆ their        │
│            ┆         ┆               ┆ of Gaza to   ┆ many ways,   ┆              ┆ relationship │
│            ┆         ┆               ┆ trusted clan ┆ but it's not ┆              ┆ with Hamas,  │
│            ┆         ┆               ┆ s/families   ┆ enough.      ┆              ┆ which        │
│            ┆         ┆               ┆ in the       ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆ strip. These ┆              ┆              ┆ relates to   │
│            ┆         ┆               ┆ groups were  ┆              ┆              ┆ the dynamics │
│            ┆         ┆               ┆ not Hamas    ┆              ┆              ┆ of the       │
│            ┆         ┆               ┆ affiliated.  ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆ Since then,  ┆              ┆              ┆ post-war con │
│            ┆         ┆               ┆ that talk    ┆              ┆              ┆ siderations. │
│            ┆         ┆               ┆ has          ┆              ┆              ┆              │
│            ┆         ┆               ┆ completely   ┆              ┆              ┆              │
│            ┆         ┆               ┆ disappeared. ┆              ┆              ┆              │
│            ┆         ┆               ┆ The only     ┆              ┆              ┆              │
│            ┆         ┆               ┆ mention I’ve ┆              ┆              ┆              │
│            ┆         ┆               ┆ seen of them ┆              ┆              ┆              │
│            ┆         ┆               ┆ lately is    ┆              ┆              ┆              │
│            ┆         ┆               ┆ that there   ┆              ┆              ┆              │
│            ┆         ┆               ┆ was a        ┆              ┆              ┆              │
│            ┆         ┆               ┆ revenge      ┆              ┆              ┆              │
│            ┆         ┆               ┆ killing by   ┆              ┆              ┆              │
│            ┆         ┆               ┆ one of these ┆              ┆              ┆              │
│            ┆         ┆               ┆ families     ┆              ┆              ┆              │
│            ┆         ┆               ┆ against a    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Hamas        ┆              ┆              ┆              │
│            ┆         ┆               ┆ operative.   ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ I’m curious, ┆              ┆              ┆              │
│            ┆         ┆               ┆ was this a   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Gallant-led  ┆              ┆              ┆              │
│            ┆         ┆               ┆ effort and   ┆              ┆              ┆              │
│            ┆         ┆               ┆ it has       ┆              ┆              ┆              │
│            ┆         ┆               ┆ disappeared  ┆              ┆              ┆              │
│            ┆         ┆               ┆ since he was ┆              ┆              ┆              │
│            ┆         ┆               ┆ dismissed    ┆              ┆              ┆              │
│            ┆         ┆               ┆ from his     ┆              ┆              ┆              │
│            ┆         ┆               ┆ position?    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Was it never ┆              ┆              ┆              │
│            ┆         ┆               ┆ really a     ┆              ┆              ┆              │
│            ┆         ┆               ┆ viable       ┆              ┆              ┆              │
│            ┆         ┆               ┆ option to    ┆              ┆              ┆              │
│            ┆         ┆               ┆ begin with?  ┆              ┆              ┆              │
│            ┆         ┆               ┆ Has anyone   ┆              ┆              ┆              │
│            ┆         ┆               ┆ seen         ┆              ┆              ┆              │
│            ┆         ┆               ┆ additional   ┆              ┆              ┆              │
│            ┆         ┆               ┆ information  ┆              ┆              ┆              │
│            ┆         ┆               ┆ about this?  ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ While I’m at ┆              ┆              ┆              │
│            ┆         ┆               ┆ it, does     ┆              ┆              ┆              │
│            ┆         ┆               ┆ anyone have  ┆              ┆              ┆              │
│            ┆         ┆               ┆ any          ┆              ┆              ┆              │
│            ┆         ┆               ┆ information  ┆              ┆              ┆              │
│            ┆         ┆               ┆ about who    ┆              ┆              ┆              │
│            ┆         ┆               ┆ these clans/ ┆              ┆              ┆              │
│            ┆         ┆               ┆ families     ┆              ┆              ┆              │
│            ┆         ┆               ┆ actually     ┆              ┆              ┆              │
│            ┆         ┆               ┆ are? It’s an ┆              ┆              ┆              │
│            ┆         ┆               ┆ interesting  ┆              ┆              ┆              │
│            ┆         ┆               ┆ alternative  ┆              ┆              ┆              │
│            ┆         ┆               ┆ solution for ┆              ┆              ┆              │
│            ┆         ┆               ┆ post-war     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Gaza.        ┆              ┆              ┆              │
└────────────┴─────────┴───────────────┴──────────────┴──────────────┴──────────────┴──────────────┘

========================================================================================================================================================================================================

CONTENT_RELEVANCE_SCORE == 5

shape: (5, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ o05l3lw    ┆ 1qfa6m3 ┆ White House   ┆              ┆ I hope that  ┆ 5            ┆ The comment  │
│            ┆         ┆ announced the ┆              ┆ Hamas will   ┆              ┆ explicitly   │
│            ┆         ┆ Gaza "board   ┆              ┆ keep ruling  ┆              ┆ discusses    │
│            ┆         ┆ of peace" of  ┆              ┆ the Gaza     ┆              ┆ Hamas's role │
│            ┆         ┆ zionists and  ┆              ┆ Strip, will  ┆              ┆ in Gaza and  │
│            ┆         ┆ war           ┆              ┆ keep         ┆              ┆ expresses    │
│            ┆         ┆ criminals,    ┆              ┆ resisting    ┆              ┆ strong       │
│            ┆         ┆ with no       ┆              ┆ against the  ┆              ┆ opinions     │
│            ┆         ┆ palestinian   ┆              ┆ abusive      ┆              ┆ about the    │
│            ┆         ┆ representatio ┆              ┆ genocidal    ┆              ┆ conflict,    │
│            ┆         ┆ n.            ┆              ┆ oppressive   ┆              ┆ including    │
│            ┆         ┆               ┆              ┆ sadistic     ┆              ┆ references   │
│            ┆         ┆               ┆              ┆ childkilling ┆              ┆ to the       │
│            ┆         ┆               ┆              ┆ genocidal    ┆              ┆ actions of   │
│            ┆         ┆               ┆              ┆ maniacs and  ┆              ┆ Zionists and │
│            ┆         ┆               ┆              ┆ Zionist      ┆              ┆ the plight   │
│            ┆         ┆               ┆              ┆ occupiers    ┆              ┆ of Palestini │
│            ┆         ┆               ┆              ┆ and that     ┆              ┆ ans, which   │
│            ┆         ┆               ┆              ┆ they will be ┆              ┆ are directly │
│            ┆         ┆               ┆              ┆ able to      ┆              ┆ related to   │
│            ┆         ┆               ┆              ┆ represent    ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆ the          ┆              ┆ conflict.    │
│            ┆         ┆               ┆              ┆ Palestinian  ┆              ┆              │
│            ┆         ┆               ┆              ┆ people in    ┆              ┆              │
│            ┆         ┆               ┆              ┆ the best way ┆              ┆              │
│            ┆         ┆               ┆              ┆ possible. I  ┆              ┆              │
│            ┆         ┆               ┆              ┆ wish only    ┆              ┆              │
│            ┆         ┆               ┆              ┆ curses and   ┆              ┆              │
│            ┆         ┆               ┆              ┆ bad things   ┆              ┆              │
│            ┆         ┆               ┆              ┆ in life for  ┆              ┆              │
│            ┆         ┆               ┆              ┆ all those    ┆              ┆              │
│            ┆         ┆               ┆              ┆ that are     ┆              ┆              │
│            ┆         ┆               ┆              ┆ plotting     ┆              ┆              │
│            ┆         ┆               ┆              ┆ against the  ┆              ┆              │
│            ┆         ┆               ┆              ┆ Palestinians ┆              ┆              │
│            ┆         ┆               ┆              ┆ to help the  ┆              ┆              │
│            ┆         ┆               ┆              ┆ Zionist      ┆              ┆              │
│            ┆         ┆               ┆              ┆ Entity in    ┆              ┆              │
│            ┆         ┆               ┆              ┆ any form     ┆              ┆              │
│            ┆         ┆               ┆              ┆ possible.    ┆              ┆              │
│ nbg8r8m    ┆ 1n3tjm5 ┆ The argument  ┆ Avraham      ┆ Eyyyy I was  ┆ 5            ┆ The comment  │
│            ┆         ┆ for why Oct.  ┆ Shalev’s     ┆ considering  ┆              ┆ engages      │
│            ┆         ┆ 7 meets the   ┆ article      ┆ making this  ┆              ┆ directly     │
│            ┆         ┆ definition of ┆ advances the ┆ post down    ┆              ┆ with the     │
│            ┆         ┆ genocide      ┆ argument     ┆ the road.    ┆              ┆ topic of     │
│            ┆         ┆ committed by  ┆ that the     ┆ Glad someone ┆              ┆ genocide in  │
│            ┆         ┆ Hamas against ┆ Hamas        ┆ did it for   ┆              ┆ relation to  │
│            ┆         ┆ Israeli Jews  ┆ assault of   ┆ me. While I  ┆              ┆ the October  │
│            ┆         ┆               ┆ October 7,   ┆ think        ┆              ┆ 7 attacks,   │
│            ┆         ┆               ┆ 2023,        ┆ personally   ┆              ┆ discussing   │
│            ┆         ┆               ┆ constitutes  ┆ (not         ┆              ┆ both the     │
│            ┆         ┆               ┆ genocide     ┆ legally)     ┆              ┆ intent of    │
│            ┆         ┆               ┆ under intern ┆ that its     ┆              ┆ Hamas and    │
│            ┆         ┆               ┆ ational law. ┆ debatable    ┆              ┆ the classifi │
│            ┆         ┆               ┆ He builds    ┆ that October ┆              ┆ cation of    │
│            ┆         ┆               ┆ his case by  ┆ 7th itself   ┆              ┆ the event,   │
│            ┆         ┆               ┆ applying the ┆ can be fully ┆              ┆ which are    │
│            ┆         ┆               ┆ two          ┆ classified   ┆              ┆ central to   │
│            ┆         ┆               ┆ essential    ┆ as a         ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ elements of  ┆ genocide, I  ┆              ┆ conflict.    │
│            ┆         ┆               ┆ genocide     ┆ think its    ┆              ┆              │
│            ┆         ┆               ┆ found in the ┆ beyond       ┆              ┆              │
│            ┆         ┆               ┆ 1948         ┆ dispute that ┆              ┆              │
│            ┆         ┆               ┆ Genocide Con ┆ Hamas had    ┆              ┆              │
│            ┆         ┆               ┆ vention—the  ┆ genocidal    ┆              ┆              │
│            ┆         ┆               ┆ physical     ┆ intent,      ┆              ┆              │
│            ┆         ┆               ┆ element      ┆ definitely   ┆              ┆              │
│            ┆         ┆               ┆ (actus reus) ┆ more         ┆              ┆              │
│            ┆         ┆               ┆ and the      ┆ compelling   ┆              ┆              │
│            ┆         ┆               ┆ mental       ┆ than what we ┆              ┆              │
│            ┆         ┆               ┆ element      ┆ see with     ┆              ┆              │
│            ┆         ┆               ┆ (dolus speci ┆ Israel. That ┆              ┆              │
│            ┆         ┆               ┆ alis)—and by ┆ coupled with ┆              ┆              │
│            ┆         ┆               ┆ highlighting ┆ their crimes ┆              ┆              │
│            ┆         ┆               ┆ the novel    ┆ against      ┆              ┆              │
│            ┆         ┆               ┆ political    ┆ humanity     ┆              ┆              │
│            ┆         ┆               ┆ tactic he    ┆ would seem   ┆              ┆              │
│            ┆         ┆               ┆ calls        ┆ to meet the  ┆              ┆              │
│            ┆         ┆               ┆ “genocide    ┆ threshold    ┆              ┆              │
│            ┆         ┆               ┆ inversion,”  ┆ for          ┆              ┆              │
│            ┆         ┆               ┆ whereby      ┆ genocide.    ┆              ┆              │
│            ┆         ┆               ┆ perpetrators ┆              ┆              ┆              │
│            ┆         ┆               ┆ accuse their ┆              ┆              ┆              │
│            ┆         ┆               ┆ victims of   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the very     ┆              ┆              ┆              │
│            ┆         ┆               ┆ crime they   ┆              ┆              ┆              │
│            ┆         ┆               ┆ themselves   ┆              ┆              ┆              │
│            ┆         ┆               ┆ have         ┆              ┆              ┆              │
│            ┆         ┆               ┆ committed.   ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ On the       ┆              ┆              ┆              │
│            ┆         ┆               ┆ physical     ┆              ┆              ┆              │
│            ┆         ┆               ┆ side, the    ┆              ┆              ┆              │
│            ┆         ┆               ┆ atrocities   ┆              ┆              ┆              │
│            ┆         ┆               ┆ carried out  ┆              ┆              ┆              │
│            ┆         ┆               ┆ on October 7 ┆              ┆              ┆              │
│            ┆         ┆               ┆ were wide-ra ┆              ┆              ┆              │
│            ┆         ┆               ┆ nging,       ┆              ┆              ┆              │
│            ┆         ┆               ┆ systematic,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and          ┆              ┆              ┆              │
│            ┆         ┆               ┆ explicitly   ┆              ┆              ┆              │
│            ┆         ┆               ┆ directed     ┆              ┆              ┆              │
│            ┆         ┆               ┆ against      ┆              ┆              ┆              │
│            ┆         ┆               ┆ civilians.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Coordinated  ┆              ┆              ┆              │
│            ┆         ┆               ┆ attacks on   ┆              ┆              ┆              │
│            ┆         ┆               ┆ 22 Israeli   ┆              ┆              ┆              │
│            ┆         ┆               ┆ towns and    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the Nova     ┆              ┆              ┆              │
│            ┆         ┆               ┆ music        ┆              ┆              ┆              │
│            ┆         ┆               ┆ festival     ┆              ┆              ┆              │
│            ┆         ┆               ┆ left more    ┆              ┆              ┆              │
│            ┆         ┆               ┆ than 1,200   ┆              ┆              ┆              │
│            ┆         ┆               ┆ civilians    ┆              ┆              ┆              │
│            ┆         ┆               ┆ dead and     ┆              ┆              ┆              │
│            ┆         ┆               ┆ thousands    ┆              ┆              ┆              │
│            ┆         ┆               ┆ more         ┆              ┆              ┆              │
│            ┆         ┆               ┆ wounded.     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Survivors    ┆              ┆              ┆              │
│            ┆         ┆               ┆ and investig ┆              ┆              ┆              │
│            ┆         ┆               ┆ ators        ┆              ┆              ┆              │
│            ┆         ┆               ┆ documented   ┆              ┆              ┆              │
│            ┆         ┆               ┆ torture,     ┆              ┆              ┆              │
│            ┆         ┆               ┆ mutilation,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ abductions,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and          ┆              ┆              ┆              │
│            ┆         ┆               ┆ systematic   ┆              ┆              ┆              │
│            ┆         ┆               ┆ sexual       ┆              ┆              ┆              │
│            ┆         ┆               ┆ violence,    ┆              ┆              ┆              │
│            ┆         ┆               ┆ including    ┆              ┆              ┆              │
│            ┆         ┆               ┆ gang rapes   ┆              ┆              ┆              │
│            ┆         ┆               ┆ and the      ┆              ┆              ┆              │
│            ┆         ┆               ┆ desecration  ┆              ┆              ┆              │
│            ┆         ┆               ┆ of bodies.   ┆              ┆              ┆              │
│            ┆         ┆               ┆ These acts   ┆              ┆              ┆              │
│            ┆         ┆               ┆ fall         ┆              ┆              ┆              │
│            ┆         ┆               ┆ squarely     ┆              ┆              ┆              │
│            ┆         ┆               ┆ under the    ┆              ┆              ┆              │
│            ┆         ┆               ┆ prohibitions ┆              ┆              ┆              │
│            ┆         ┆               ┆ of Article   ┆              ┆              ┆              │
│            ┆         ┆               ┆ II of the    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Convention,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ which…       ┆              ┆              ┆              │
│ ngc48y6    ┆ 1nr5tx7 ┆ israelis      ┆              ┆ Fuck IDF     ┆ 5            ┆ The comment  │
│            ┆         ┆ shoot a       ┆              ┆ terrorists!  ┆              ┆ expresses a  │
│            ┆         ┆ palestinian   ┆              ┆              ┆              ┆ strong       │
│            ┆         ┆ teen after    ┆              ┆              ┆              ┆ opinion      │
│            ┆         ┆ they tell him ┆              ┆              ┆              ┆ about the    │
│            ┆         ┆ to walk away. ┆              ┆              ┆              ┆ IDF in the   │
│            ┆         ┆               ┆              ┆              ┆              ┆ context of   │
│            ┆         ┆               ┆              ┆              ┆              ┆ violence     │
│            ┆         ┆               ┆              ┆              ┆              ┆ against a    │
│            ┆         ┆               ┆              ┆              ┆              ┆ Palestinian  │
│            ┆         ┆               ┆              ┆              ┆              ┆ teen,        │
│            ┆         ┆               ┆              ┆              ┆              ┆ directly     │
│            ┆         ┆               ┆              ┆              ┆              ┆ relating to  │
│            ┆         ┆               ┆              ┆              ┆              ┆ the core     │
│            ┆         ┆               ┆              ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆              ┆              ┆              ┆ events       │
│            ┆         ┆               ┆              ┆              ┆              ┆ occurring in │
│            ┆         ┆               ┆              ┆              ┆              ┆ Gaza.        │
│ niszq4p    ┆ 1o2r9ga ┆ Your silence  ┆ All          ┆ I’m glad     ┆ 5            ┆ The comment  │
│            ┆         ┆ is deafening  ┆ supposedly   ┆ there’s a    ┆              ┆ addresses    │
│            ┆         ┆               ┆ pro-Palestin ┆ peace deal,  ┆              ┆ the ongoing  │
│            ┆         ┆               ┆ ian          ┆ but Israel   ┆              ┆ violence     │
│            ┆         ┆               ┆ activists    ┆ is currently ┆              ┆ against      │
│            ┆         ┆               ┆ who are      ┆ still        ┆              ┆ Palestinian  │
│            ┆         ┆               ┆ silent on    ┆ bombing and  ┆              ┆ civilians    │
│            ┆         ┆               ┆ the proposed ┆ shooting at  ┆              ┆ amidst       │
│            ┆         ┆               ┆ peace deal   ┆ Palestinian  ┆              ┆ discussions  │
│            ┆         ┆               ┆ which would  ┆ civilians    ┆              ┆ of a peace   │
│            ┆         ┆               ┆ provide the  ┆ trying to    ┆              ┆ deal,        │
│            ┆         ┆               ┆ short term   ┆ return home. ┆              ┆ directly     │
│            ┆         ┆               ┆ ceasefire    ┆              ┆              ┆ relating to  │
│            ┆         ┆               ┆ you claim    ┆              ┆              ┆ the          │
│            ┆         ┆               ┆ you wanted   ┆              ┆              ┆ humanitarian │
│            ┆         ┆               ┆ as well as,  ┆              ┆              ┆ impact of    │
│            ┆         ┆               ┆ prevention   ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ of any       ┆              ┆              ┆ conflict and │
│            ┆         ┆               ┆ annexation   ┆              ┆              ┆ the actions  │
│            ┆         ┆               ┆ of Gaza and  ┆              ┆              ┆ of Israel.   │
│            ┆         ┆               ┆ bring in     ┆              ┆              ┆              │
│            ┆         ┆               ┆ massive aid  ┆              ┆              ┆              │
│            ┆         ┆               ┆ into Gaza in ┆              ┆              ┆              │
│            ┆         ┆               ┆ the short    ┆              ┆              ┆              │
│            ┆         ┆               ┆ term and     ┆              ┆              ┆              │
│            ┆         ┆               ┆ long term -  ┆              ┆              ┆              │
│            ┆         ┆               ┆ your silence ┆              ┆              ┆              │
│            ┆         ┆               ┆ is           ┆              ┆              ┆              │
│            ┆         ┆               ┆ deafening.   ┆              ┆              ┆              │

========================================================================================================================================================================================================

In [ ]:
processed_df.filter(pl.col('content_relevance_score') < 3)

shape: (72_166, 7)
┌────────────┬─────────┬───────────────┬──────────────┬──────────────┬──────────────┬──────────────┐
│ comment_id ┆ post_id ┆ post_title    ┆ post_body    ┆ comment_body ┆ content_rele ┆ reasoning_co │
│ ---        ┆ ---     ┆ ---           ┆ ---          ┆ ---          ┆ vance_score  ┆ ntent_releva │
│ str        ┆ str     ┆ str           ┆ str          ┆ str          ┆ ---          ┆ nce_score    │
│            ┆         ┆               ┆              ┆              ┆ i64          ┆ ---          │
│            ┆         ┆               ┆              ┆              ┆              ┆ str          │
╞════════════╪═════════╪═══════════════╪══════════════╪══════════════╪══════════════╪══════════════╡
│ n11hxav    ┆ 1lloezh ┆ How can       ┆ New Haaretz  ┆ Because it   ┆ 2            ┆ The comment  │
│            ┆         ┆ anyone still  ┆ investigatio ┆ isn't one, a ┆              ┆ dismisses    │
│            ┆         ┆ deny it's a   ┆ n: Israeli   ┆ genocide is  ┆              ┆ the characte │
│            ┆         ┆ genocide in   ┆ soldiers     ┆ when a       ┆              ┆ rization of  │
│            ┆         ┆ Gaza?         ┆ have         ┆ government   ┆              ┆ the          │
│            ┆         ┆               ┆ provided     ┆ or group is  ┆              ┆ situation in │
│            ┆         ┆               ┆ shocking     ┆ purposely    ┆              ┆ Gaza as      │
│            ┆         ┆               ┆ testimonials ┆ setting out  ┆              ┆ genocide,    │
│            ┆         ┆               ┆ of the state ┆ to kill      ┆              ┆ framing it   │
│            ┆         ┆               ┆ of           ┆ everyone ind ┆              ┆ instead as a │
│            ┆         ┆               ┆ operations   ┆ iscriminatel ┆              ┆ consequence  │
│            ┆         ┆               ┆ in Gaza.     ┆ y like the   ┆              ┆ of war,      │
│            ┆         ┆               ┆              ┆ holocaust,   ┆              ┆ which        │
│            ┆         ┆               ┆ One IDF      ┆ this is just ┆              ┆ reflects a   │
│            ┆         ┆               ┆ solider      ┆ war and in   ┆              ┆ specific     │
│            ┆         ┆               ┆ said:        ┆ war there    ┆              ┆ opinion on   │
│            ┆         ┆               ┆ > We open    ┆ will always  ┆              ┆ the          │
│            ┆         ┆               ┆ fire early   ┆ be deaths of ┆              ┆ conflict.    │
│            ┆         ┆               ┆ in the       ┆ civilians.   ┆              ┆ However, it  │
│            ┆         ┆               ┆ morning if   ┆ This is      ┆              ┆ does not     │
│            ┆         ┆               ┆ someone      ┆ unfortunate  ┆              ┆ engage with  │
│            ┆         ┆               ┆ tries to get ┆ but anyone   ┆              ┆ the core     │
│            ┆         ┆               ┆ in line from ┆ with a       ┆              ┆ humanitarian │
│            ┆         ┆               ┆ a few        ┆ logical      ┆              ┆ issues or    │
│            ┆         ┆               ┆ hundred      ┆ brain knows  ┆              ┆ the direct   │
│            ┆         ┆               ┆ meters away, ┆ israel could ┆              ┆ actions      │
│            ┆         ┆               ┆ and          ┆ have done    ┆              ┆ described in │
│            ┆         ┆               ┆ sometimes we ┆ far worse to ┆              ┆ the original │
│            ┆         ┆               ┆ just charge  ┆ gaza if they ┆              ┆ post, making │
│            ┆         ┆               ┆ at them from ┆ were truly   ┆              ┆ it less      │
│            ┆         ┆               ┆ close range. ┆ hell bent on ┆              ┆ relevant.    │
│            ┆         ┆               ┆ But there's  ┆ evil, they   ┆              ┆              │
│            ┆         ┆               ┆ no danger to ┆ have the     ┆              ┆              │
│            ┆         ┆               ┆ the forces.  ┆ firepower to ┆              ┆              │
│            ┆         ┆               ┆ I'm not      ┆ erase the    ┆              ┆              │
│            ┆         ┆               ┆ aware of a   ┆ gaza strip   ┆              ┆              │
│            ┆         ┆               ┆ single       ┆ in a couple  ┆              ┆              │
│            ┆         ┆               ┆ instance of  ┆ days easily. ┆              ┆              │
│            ┆         ┆               ┆ return fire. ┆              ┆              ┆              │
│            ┆         ┆               ┆ There's no   ┆              ┆              ┆              │
│            ┆         ┆               ┆ enemy, no    ┆              ┆              ┆              │
│            ┆         ┆               ┆ weapons.     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Another      ┆              ┆              ┆              │
│            ┆         ┆               ┆ described    ┆              ┆              ┆              │
│            ┆         ┆               ┆ the area     ┆              ┆              ┆              │
│            ┆         ┆               ┆ near the     ┆              ┆              ┆              │
│            ┆         ┆               ┆ food trucks  ┆              ┆              ┆              │
│            ┆         ┆               ┆ as “a        ┆              ┆              ┆              │
│            ┆         ┆               ┆ killing      ┆              ┆              ┆              │
│            ┆         ┆               ┆ field.”      ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ > Where I    ┆              ┆              ┆              │
│            ┆         ┆               ┆ was          ┆              ┆              ┆              │
│            ┆         ┆               ┆ stationed,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ between one  ┆              ┆              ┆              │
│            ┆         ┆               ┆ and five     ┆              ┆              ┆              │
│            ┆         ┆               ┆ people were  ┆              ┆              ┆              │
│            ┆         ┆               ┆ killed every ┆              ┆              ┆              │
│            ┆         ┆               ┆ day. They're ┆              ┆              ┆              │
│            ┆         ┆               ┆ treated like ┆              ┆              ┆              │
│            ┆         ┆               ┆ a hostile    ┆              ┆              ┆              │
│            ┆         ┆               ┆ force – no   ┆              ┆              ┆              │
│            ┆         ┆               ┆ crowd-contro ┆              ┆              ┆              │
│            ┆         ┆               ┆ l measures,  ┆              ┆              ┆              │
│            ┆         ┆               ┆ no tear gas  ┆              ┆              ┆              │
│            ┆         ┆               ┆ – just live  ┆              ┆              ┆              │
│            ┆         ┆               ┆ fire with    ┆              ┆              ┆              │
│            ┆         ┆               ┆ everything   ┆              ┆              ┆              │
│            ┆         ┆               ┆ imaginable:  ┆              ┆              ┆              │
│            ┆         ┆               ┆ heavy        ┆              ┆              ┆              │
│            ┆         ┆               ┆ machine      ┆              ┆              ┆              │
│            ┆         ┆               ┆ guns,        ┆              ┆              ┆              │
│            ┆         ┆               ┆ grenade      ┆              ┆              ┆              │
│            ┆         ┆               ┆ launchers,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ mortars.     ┆              ┆              ┆              │
│            ┆         ┆               ┆ Then, once   ┆              ┆              ┆              │
│            ┆         ┆               ┆ the center   ┆              ┆              ┆              │
│            ┆         ┆               ┆ opens, the   ┆              ┆              ┆              │
│            ┆         ┆               ┆ shooting     ┆              ┆              ┆              │
│            ┆         ┆               ┆ stops, and   ┆              ┆              ┆              │
│            ┆         ┆               ┆ they know    ┆              ┆              ┆              │
│            ┆         ┆               ┆ they can     ┆              ┆              ┆              │
│            ┆         ┆               ┆ approach.    ┆              ┆              ┆              │
│            ┆         ┆               ┆ Our form of  ┆              ┆              ┆              │
│            ┆         ┆               ┆ communicatio ┆              ┆              ┆              │
│            ┆         ┆               ┆ n is         ┆              ┆              ┆              │
│            ┆         ┆               ┆ gunfire.     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Yet another  ┆              ┆              ┆              │
│            ┆         ┆               ┆ soldier      ┆              ┆              ┆              │
│            ┆         ┆               ┆ stated       ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ >            ┆              ┆              ┆              │
│            ┆         ┆               ┆ Technically, ┆              ┆              ┆              │
│            ┆         ┆               ┆ it's         ┆              ┆              ┆              │
│            ┆         ┆               ┆ supposed to  ┆              ┆              ┆              │
│            ┆         ┆               ┆ be warning   ┆              ┆              ┆              │
│            ┆         ┆               ┆ fire –       ┆              ┆              ┆              │
│            ┆         ┆               ┆ either to    ┆              ┆              ┆              │
│            ┆         ┆               ┆ push people  ┆              ┆              ┆              │
│            ┆         ┆               ┆ back or stop ┆              ┆              ┆              │
│            ┆         ┆               ┆ them from    ┆              ┆              ┆              │
│            ┆         ┆               ┆ advancing,"  ┆              ┆              ┆              │
│            ┆         ┆               ┆ he said.     ┆              ┆              ┆              │
│            ┆         ┆               ┆ "But…        ┆              ┆              ┆              │
│ mu58xtn    ┆ 1ku8sal ┆ No words      ┆              ┆ Even the     ┆ 0            ┆ The comment  │
│            ┆         ┆               ┆              ┆ stats on it  ┆              ┆ does not     │
│            ┆         ┆               ┆              ┆ are fake .   ┆              ┆ address the  │
│            ┆         ┆               ┆              ┆ More         ┆              ┆ Gaza         │
│            ┆         ┆               ┆              ┆ comments     ┆              ┆ conflict or  │
│            ┆         ┆               ┆              ┆ than likes   ┆              ┆ any related  │
│            ┆         ┆               ┆              ┆ 🤣🤣🤣       ┆              ┆ topics,      │
│            ┆         ┆               ┆              ┆              ┆              ┆ focusing     │
│            ┆         ┆               ┆              ┆              ┆              ┆ instead on   │
│            ┆         ┆               ┆              ┆              ┆              ┆ social media │
│            ┆         ┆               ┆              ┆              ┆              ┆ engagement   │
│            ┆         ┆               ┆              ┆              ┆              ┆ metrics,     │
│            ┆         ┆               ┆              ┆              ┆              ┆ which is     │
│            ┆         ┆               ┆              ┆              ┆              ┆ irrelevant   │
│            ┆         ┆               ┆              ┆              ┆              ┆ to the       │
│            ┆         ┆               ┆              ┆              ┆              ┆ study.       │
│ n61xsyu    ┆ 1mdi98j ┆ Jon Stewart   ┆ I watched    ┆ Let me guess ┆ 2            ┆ The comment  │
│            ┆         ┆ called Israel ┆ Peter        ┆ John Stewart ┆              ┆ dismisses    │
│            ┆         ┆ a failure of  ┆ Beinart on   ┆ is Hamas     ┆              ┆ Jon          │
│            ┆         ┆ humanity.     ┆ Jon Stewart, ┆ Propaganda   ┆              ┆ Stewart's    │
│            ┆         ┆ Beinart let   ┆ and while I  ┆              ┆              ┆ views by     │
│            ┆         ┆ It slide. An  ┆ respect      ┆              ┆              ┆ labeling     │
│            ┆         ┆ opportunity   ┆ parts of his ┆              ┆              ┆ them as      │
│            ┆         ┆ missed.       ┆ moral        ┆              ┆              ┆ Hamas        │
│            ┆         ┆               ┆ appeal, his  ┆              ┆              ┆ propaganda,  │
│            ┆         ┆               ┆ framing      ┆              ┆              ┆ which        │
│            ┆         ┆               ┆ reveals a    ┆              ┆              ┆ reflects a   │
│            ┆         ┆               ┆ dangerous    ┆              ┆              ┆ polarized    │
│            ┆         ┆               ┆ naivety.     ┆              ┆              ┆ opinion on   │
│            ┆         ┆               ┆ Especially   ┆              ┆              ┆ the Gaza     │
│            ┆         ┆               ┆ for those of ┆              ┆              ┆ conflict but │
│            ┆         ┆               ┆ us who’ve    ┆              ┆              ┆ does not     │
│            ┆         ┆               ┆ worked in    ┆              ┆              ┆ engage with  │
│            ┆         ┆               ┆ developing   ┆              ┆              ┆ the core     │
│            ┆         ┆               ┆ countries,   ┆              ┆              ┆ issues or    │
│            ┆         ┆               ┆ engaged with ┆              ┆              ┆ provide      │
│            ┆         ┆               ┆ the          ┆              ┆              ┆ substantial  │
│            ┆         ┆               ┆ Palestinian  ┆              ┆              ┆ insight into │
│            ┆         ┆               ┆ movement,    ┆              ┆              ┆ the conflict │
│            ┆         ┆               ┆ and          ┆              ┆              ┆ itself.      │
│            ┆         ┆               ┆ understand   ┆              ┆              ┆              │
│            ┆         ┆               ┆ what Zionism ┆              ┆              ┆              │
│            ┆         ┆               ┆ actually     ┆              ┆              ┆              │
│            ┆         ┆               ┆ responds to. ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ **Full       ┆              ┆              ┆              │
│            ┆         ┆               ┆ thoughts     ┆              ┆              ┆              │
│            ┆         ┆               ┆ below.**     ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jon Stewart  ┆              ┆              ┆              │
│            ┆         ┆               ┆ said         ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel’s     ┆              ┆              ┆              │
│            ┆         ┆               ┆ existence is ┆              ┆              ┆              │
│            ┆         ┆               ┆ a “failure   ┆              ┆              ┆              │
│            ┆         ┆               ┆ of           ┆              ┆              ┆              │
│            ┆         ┆               ┆ humanity.”   ┆              ┆              ┆              │
│            ┆         ┆               ┆ And you know ┆              ┆              ┆              │
│            ┆         ┆               ┆ what? He     ┆              ┆              ┆              │
│            ┆         ┆               ┆ might be     ┆              ┆              ┆              │
│            ┆         ┆               ┆ right - but  ┆              ┆              ┆              │
│            ┆         ┆               ┆ not how he   ┆              ┆              ┆              │
│            ┆         ┆               ┆ means it.    ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ The failure  ┆              ┆              ┆              │
│            ┆         ┆               ┆ isn’t that   ┆              ┆              ┆              │
│            ┆         ┆               ┆ Israel       ┆              ┆              ┆              │
│            ┆         ┆               ┆ exists. It’s ┆              ┆              ┆              │
│            ┆         ┆               ┆ that it *has ┆              ┆              ┆              │
│            ┆         ┆               ┆ to*.         ┆              ┆              ┆              │
│            ┆         ┆               ┆              ┆              ┆              ┆              │
│            ┆         ┆               ┆ After        ┆              ┆              ┆              │
│            ┆         ┆               ┆ millennia of ┆              ┆              ┆              │
│            ┆         ┆               ┆ persecution, ┆              ┆              ┆              │
│            ┆         ┆               ┆ pogroms,     ┆              ┆              ┆              │
│            ┆         ┆               ┆ ghettos,     ┆              ┆              ┆              │
│            ┆         ┆               ┆ ethnic       ┆              ┆              ┆              │
│            ┆         ┆               ┆ cleansing,   ┆              ┆              ┆              │
│            ┆         ┆               ┆ and global   ┆              ┆              ┆              │
│            ┆         ┆               ┆ apathy       ┆              ┆              ┆              │
│            ┆         ┆               ┆ toward our   ┆              ┆              ┆              │
│            ┆         ┆               ┆ slaughter... ┆              ┆              ┆              │
│            ┆         ┆               ┆ Jews had no  ┆              ┆              ┆              │
│            ┆         ┆               ┆ choice but   ┆              ┆              ┆              │
│            ┆         ┆               ┆ to build a   ┆              ┆              ┆              │