In [76]:
import os
import polars as pl

In [77]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..', '..')
features_dir = os.path.join(project_path, 'data', 'features')
feature_file_path = os.path.join(features_dir, 'content_relevance_score.parquet')
feature_df = pl.read_parquet(feature_file_path)

In [78]:
# 1. Mostrar el contenido completo de los strings (sin límite)
pl.Config.set_fmt_str_lengths(1000) # Ajusta al largo que necesites

polars.config.Config

In [79]:
feature_df

shape: (15_750, 3)
┌────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_score                         │
│ ---        ┆ ---                     ┆ ---                                                       │
│ str        ┆ i64                     ┆ str                                                       │
╞════════════╪═════════════════════════╪═══════════════════════════════════════════════════════════╡
│ mzlqxrg    ┆ 4                       ┆ The comment expresses a desire for Iran to take military  │
│            ┆                         ┆ action against Israel in the context of humanitarian aid, │
│            ┆                         ┆ which relates directly to the ongoing conflict and its    │
│            ┆                         ┆ implications for Gaza.                                    │
│ obbcoq3    ┆ 0                       ┆ The comment is vague and does not provide any specific    │
│            ┆                         ┆ information or opinion related to the Gaza conflict,      │
│            ┆                         ┆ focusing instead on a general statement about truth       │
│            ┆                         ┆ without context.                                          │
│ n9yjtzg    ┆ 2                       ┆ The comment reflects on the hostility faced by Jews in    │
│            ┆                         ┆ Barcelona, linking it to broader themes of antisemitism   │
│            ┆                         ┆ and public sentiment related to the Gaza conflict, but it │
│            ┆                         ┆ does not directly address the conflict itself or its core │
│            ┆                         ┆ events.                                                   │
│ nax2wzf    ┆ 1                       ┆ The comment focuses on a political strategy regarding the │
│            ┆                         ┆ Democratic Party in the context of the Gaza conflict, but │
│            ┆                         ┆ it does not directly address the humanitarian situation   │
│            ┆                         ┆ or the core events of the conflict itself. It is more     │
│            ┆                         ┆ about U.S. internal politics than the Gaza conflict.      │
│ n8vxcji    ┆ 3                       ┆ The comment reflects on a historical event related to     │
│            ┆                         ┆ Israel's actions in Gaza and connects it to current       │
│            ┆                         ┆ events, indicating a perspective on the conflict's        │
│            ┆                         ┆ implications. However, it does not engage with the core   │
│            ┆                         ┆ conflict or humanitarian issues directly.                 │
│ …          ┆ …                       ┆ …                                                         │
│ np13vuq    ┆ 0                       ┆ Primary subject is US domestic politics/Ben Shapiro and a │
│            ┆                         ┆ critique of socioeconomic and racial exclusion in         │
│            ┆                         ┆ America, not the Gaza conflict or related actors; per the │
│            ┆                         ┆ guidelines this is unrelated and should be discarded.     │
│ n60o29h    ┆ 4                       ┆ The comment is a direct reaction to a statement by the    │
│            ┆                         ┆ Israeli ambassador to Germany, reflecting opinion about   │
│            ┆                         ┆ an Israeli official's messaging; this is                  │
│            ┆                         ┆ media/opinion-level content related to the Israel/Gaza    │
│            ┆                         ┆ situation. Under the scale, this constitutes 'Clearly     │
│            ┆                         ┆ Related' (media/public opinion) rather than core conflict │
│            ┆                         ┆ reporting.                                                │
│ n4h5j94    ┆ 4                       ┆ The comment discusses alleged Israeli psyops, Zionist     │
│            ┆                         ┆ tactics, and antisemitism aimed at discrediting           │
│            ┆                         ┆ opposition to Israel—primary subject: public              │
│            ┆                         ┆ opinion/propaganda related to the Israel-Palestine        │
│            ┆                         ┆ conflict. This directly pertains to media/opinion and     │
│            ┆                         ┆ actor behavior around the conflict rather than            │
│            ┆                         ┆ battlefield events, so it fits 'Clearly Related'.         │
│ n5xfc99    ┆ 4                       ┆ The comment discusses public opinion about support for    │
│            ┆                         ┆ Gaza versus Israel and contrasts platform differences     │
│            ┆                         ┆ (Reddit vs X), making it centered on media/perception of  │
│            ┆                         ┆ the conflict. This fits the 'Clearly Related' category    │
│            ┆                         ┆ (public opinion/media coverage), so it merits a 4.        │
│ n8llnry    ┆ 4                       ┆ The single-word comment 'Pallywood' accuses staged/media  │
│            ┆                         ┆ manipulation related to Palestinian coverage, so its      │
│            ┆                         ┆ primary subject is media depiction of the Gaza conflict.  │
│            ┆                         ┆ This targets media coverage of the conflict and thus fits │
│            ┆                         ┆ the 'Clearly Related (Media, Opinion, Relations)'         │
│            ┆                         ┆ category.                                                 │
└────────────┴─────────────────────────┴───────────────────────────────────────────────────────────┘

In [80]:
feature_df

shape: (15_750, 3)
┌────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_score                         │
│ ---        ┆ ---                     ┆ ---                                                       │
│ str        ┆ i64                     ┆ str                                                       │
╞════════════╪═════════════════════════╪═══════════════════════════════════════════════════════════╡
│ mzlqxrg    ┆ 4                       ┆ The comment expresses a desire for Iran to take military  │
│            ┆                         ┆ action against Israel in the context of humanitarian aid, │
│            ┆                         ┆ which relates directly to the ongoing conflict and its    │
│            ┆                         ┆ implications for Gaza.                                    │
│ obbcoq3    ┆ 0                       ┆ The comment is vague and does not provide any specific    │
│            ┆                         ┆ information or opinion related to the Gaza conflict,      │
│            ┆                         ┆ focusing instead on a general statement about truth       │
│            ┆                         ┆ without context.                                          │
│ n9yjtzg    ┆ 2                       ┆ The comment reflects on the hostility faced by Jews in    │
│            ┆                         ┆ Barcelona, linking it to broader themes of antisemitism   │
│            ┆                         ┆ and public sentiment related to the Gaza conflict, but it │
│            ┆                         ┆ does not directly address the conflict itself or its core │
│            ┆                         ┆ events.                                                   │
│ nax2wzf    ┆ 1                       ┆ The comment focuses on a political strategy regarding the │
│            ┆                         ┆ Democratic Party in the context of the Gaza conflict, but │
│            ┆                         ┆ it does not directly address the humanitarian situation   │
│            ┆                         ┆ or the core events of the conflict itself. It is more     │
│            ┆                         ┆ about U.S. internal politics than the Gaza conflict.      │
│ n8vxcji    ┆ 3                       ┆ The comment reflects on a historical event related to     │
│            ┆                         ┆ Israel's actions in Gaza and connects it to current       │
│            ┆                         ┆ events, indicating a perspective on the conflict's        │
│            ┆                         ┆ implications. However, it does not engage with the core   │
│            ┆                         ┆ conflict or humanitarian issues directly.                 │
│ …          ┆ …                       ┆ …                                                         │
│ np13vuq    ┆ 0                       ┆ Primary subject is US domestic politics/Ben Shapiro and a │
│            ┆                         ┆ critique of socioeconomic and racial exclusion in         │
│            ┆                         ┆ America, not the Gaza conflict or related actors; per the │
│            ┆                         ┆ guidelines this is unrelated and should be discarded.     │
│ n60o29h    ┆ 4                       ┆ The comment is a direct reaction to a statement by the    │
│            ┆                         ┆ Israeli ambassador to Germany, reflecting opinion about   │
│            ┆                         ┆ an Israeli official's messaging; this is                  │
│            ┆                         ┆ media/opinion-level content related to the Israel/Gaza    │
│            ┆                         ┆ situation. Under the scale, this constitutes 'Clearly     │
│            ┆                         ┆ Related' (media/public opinion) rather than core conflict │
│            ┆                         ┆ reporting.                                                │
│ n4h5j94    ┆ 4                       ┆ The comment discusses alleged Israeli psyops, Zionist     │
│            ┆                         ┆ tactics, and antisemitism aimed at discrediting           │
│            ┆                         ┆ opposition to Israel—primary subject: public              │
│            ┆                         ┆ opinion/propaganda related to the Israel-Palestine        │
│            ┆                         ┆ conflict. This directly pertains to media/opinion and     │
│            ┆                         ┆ actor behavior around the conflict rather than            │
│            ┆                         ┆ battlefield events, so it fits 'Clearly Related'.         │
│ n5xfc99    ┆ 4                       ┆ The comment discusses public opinion about support for    │
│            ┆                         ┆ Gaza versus Israel and contrasts platform differences     │
│            ┆                         ┆ (Reddit vs X), making it centered on media/perception of  │
│            ┆                         ┆ the conflict. This fits the 'Clearly Related' category    │
│            ┆                         ┆ (public opinion/media coverage), so it merits a 4.        │
│ n8llnry    ┆ 4                       ┆ The single-word comment 'Pallywood' accuses staged/media  │
│            ┆                         ┆ manipulation related to Palestinian coverage, so its      │
│            ┆                         ┆ primary subject is media depiction of the Gaza conflict.  │
│            ┆                         ┆ This targets media coverage of the conflict and thus fits │
│            ┆                         ┆ the 'Clearly Related (Media, Opinion, Relations)'         │
│            ┆                         ┆ category.                                                 │
└────────────┴─────────────────────────┴───────────────────────────────────────────────────────────┘

In [83]:
feature_df['content_relevance_score'].value_counts().sort('count', descending=True)

shape: (7, 2)
┌─────────────────────────┬───────┐
│ content_relevance_score ┆ count │
│ ---                     ┆ ---   │
│ i64                     ┆ u32   │
╞═════════════════════════╪═══════╡
│ 4                       ┆ 4265  │
│ 5                       ┆ 3389  │
│ 0                       ┆ 2739  │
│ 2                       ┆ 2417  │
│ 1                       ┆ 1560  │
│ 3                       ┆ 1374  │
│ -1                      ┆ 6     │
└─────────────────────────┴───────┘

In [85]:
feature_df.filter(pl.col('content_relevance_score') < 0)

shape: (6, 3)
┌────────────┬─────────────────────────┬───────────────────────────────────────────────────────────┐
│ comment_id ┆ content_relevance_score ┆ reasoning_content_relevance_score                         │
│ ---        ┆ ---                     ┆ ---                                                       │
│ str        ┆ i64                     ┆ str                                                       │
╞════════════╪═════════════════════════╪═══════════════════════════════════════════════════════════╡
│ oaxrhwt    ┆ -1                      ┆ The comment is a short insult/nickname (                  │
│ n8mj7ql    ┆ -1                      ┆ The comment is meta-Reddit moderation/attention (         │
│ n7xwa20    ┆ -1                      ┆ The comment is a one-line expression of agreement (       │
│ npf2aoc    ┆ -1                      ┆ The comment is a terse, generic rebuttal (                │
│ ocakh06    ┆ -1                      ┆ Primary subject: accusation of supporting a 'genocidal    │
│            ┆                         ┆ entity' (core Gaza/Israel conflict) at a London location; │
│            ┆                         ┆ the comment (                                             │
│ obdjlkj    ┆ -1                      ┆ The comment is a brief partisan remark about Democrats (  │
└────────────┴─────────────────────────┴───────────────────────────────────────────────────────────┘

In [84]:
count_relevant_content = sum(feature_df['content_relevance_score'] >= 3) 
content_size = len(feature_df)
prop_relevant_content = count_relevant_content / content_size
print(f"Count relevant content: {count_relevant_content}")
print(f"Percentage relevant content: {round(prop_relevant_content * 100, 2)}%")

Count relevant content: 9028
Percentage relevant content: 57.32%