In [20]:
import os
import polars as pl

In [21]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')

feature_df_dict = {}
for filename in os.listdir(features_dir):
    name, extension = os.path.splitext(filename) 
    if 'content_relevance_score' not in name and extension == '.parquet':
        path = os.path.join(features_dir, filename)
        feature_df_dict[filename.split('.')[0]] = pl.read_parquet(path)

In [22]:
feature_df_dict.keys()

dict_keys(['argument_quality_score', 'discourse_tone_score', 'dominant_frame_score', 'political_stance_score', 'sentiment_score'])

In [23]:
feature_df = feature_df_dict['argument_quality_score']
feature_df

shape: (32, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ argument_quality_score ┆ reasoning_argument_quality_sco… │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ i64                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ ndj18f6    ┆ 2                      ┆ The comment presents a basic o… │
│ njalw5c    ┆ 2                      ┆ The comment presents a clear o… │
│ nm4anua    ┆ 1                      ┆ The comment expresses a clear … │
│ nja4ar2    ┆ 3                      ┆ The comment presents a justifi… │
│ njd5jxd    ┆ 1                      ┆ The comment expresses a strong… │
│ …          ┆ …                      ┆ …                               │
│ njaced6    ┆ 3                      ┆ The comment presents a positio… │
│ njetwvu    ┆ 2                      ┆ The comment presents a basic o… │
│ njamm7j    ┆ 3                      ┆ The comment presents a clear o… │
│ nm5s9n9    ┆ 1                      ┆ The comment is a low-quality r… │
│ nm3so23    ┆ 2                      ┆ The comment provides a source … │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [24]:
feature_df['argument_quality_score'].value_counts()

shape: (4, 2)
┌────────────────────────┬───────┐
│ argument_quality_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 2                      ┆ 16    │
│ 1                      ┆ 10    │
│ 3                      ┆ 5     │
│ 4                      ┆ 1     │
└────────────────────────┴───────┘

In [25]:
feature_df = feature_df_dict['discourse_tone_score']
feature_df

shape: (32, 3)
┌────────────┬──────────────────────┬─────────────────────────────────┐
│ comment_id ┆ discourse_tone_score ┆ reasoning_discourse_tone_score  │
│ ---        ┆ ---                  ┆ ---                             │
│ str        ┆ str                  ┆ str                             │
╞════════════╪══════════════════════╪═════════════════════════════════╡
│ ndj18f6    ┆ Analytical           ┆ The comment uses a comparison … │
│ njalw5c    ┆ Analytical           ┆ The user acknowledges a positi… │
│ nm4anua    ┆ Sarcastic            ┆ The comment expresses a mix of… │
│ nja4ar2    ┆ Analytical           ┆ The comment presents factual i… │
│ njd5jxd    ┆ Emotional            ┆ The comment expresses a sense … │
│ …          ┆ …                    ┆ …                               │
│ njaced6    ┆ Analytical           ┆ The user presents a critical a… │
│ njetwvu    ┆ Sarcastic            ┆ The comment employs sarcasm to… │
│ njamm7j    ┆ Hostile              ┆ The comment expresses a strong… │
│ nm5s9n9    ┆ Hostile              ┆ The comment expresses a clear … │
│ nm3so23    ┆ Hostile              ┆ The comment escalates the inte… │
└────────────┴──────────────────────┴─────────────────────────────────┘

In [26]:
feature_df['discourse_tone_score'].value_counts()

shape: (6, 2)
┌──────────────────────┬───────┐
│ discourse_tone_score ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ Sarcastic            ┆ 5     │
│ Analytical           ┆ 10    │
│ Hostile              ┆ 9     │
│ Other                ┆ 3     │
│ Emotional            ┆ 4     │
│ Informative          ┆ 1     │
└──────────────────────┴───────┘

In [27]:
feature_df = feature_df_dict['dominant_frame_score']
feature_df

shape: (32, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ dominant_frame_score   ┆ reasoning_dominant_frame_score  │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ str                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ ndj18f6    ┆ Geopolitical/Political ┆ The text discusses the politic… │
│ njalw5c    ┆ Geopolitical/Political ┆ The comment emphasizes the ong… │
│ nm4anua    ┆ Humanitarian/Legal     ┆ The comment highlights accusat… │
│ nja4ar2    ┆ Humanitarian/Legal     ┆ The focus on detainees held wi… │
│ njd5jxd    ┆ Geopolitical/Political ┆ The comment suggests a belief … │
│ …          ┆ …                      ┆ …                               │
│ njaced6    ┆ Historical/Religious   ┆ The text discusses territorial… │
│ njetwvu    ┆ Security/Military      ┆ The comment discusses the comp… │
│ njamm7j    ┆ Security/Military      ┆ The comment focuses on Hamas's… │
│ nm5s9n9    ┆ Humanitarian/Legal     ┆ The comment focuses on accusat… │
│ nm3so23    ┆ Humanitarian/Legal     ┆ The comment highlights the ext… │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [28]:
feature_df['dominant_frame_score'].value_counts()

shape: (4, 2)
┌────────────────────────┬───────┐
│ dominant_frame_score   ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ Historical/Religious   ┆ 5     │
│ Geopolitical/Political ┆ 10    │
│ Security/Military      ┆ 7     │
│ Humanitarian/Legal     ┆ 10    │
└────────────────────────┴───────┘

In [29]:
feature_df = feature_df_dict['political_stance_score']
feature_df

shape: (32, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ political_stance_score ┆ reasoning_political_stance_sco… │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ i64                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ ndj18f6    ┆ 3                      ┆ The comment draws a parallel b… │
│ njalw5c    ┆ 2                      ┆ The comment highlights the ong… │
│ nm4anua    ┆ 2                      ┆ The comment expresses agreemen… │
│ nja4ar2    ┆ 2                      ┆ The comment highlights issues … │
│ njd5jxd    ┆ 3                      ┆ The comment expresses a pessim… │
│ …          ┆ …                      ┆ …                               │
│ njaced6    ┆ 2                      ┆ The comment critiques Netanyah… │
│ njetwvu    ┆ 4                      ┆ The comment attempts to underm… │
│ njamm7j    ┆ 4                      ┆ The comment focuses on Hamas's… │
│ nm5s9n9    ┆ 5                      ┆ The comment dismisses criticis… │
│ nm3so23    ┆ 1                      ┆ The comment frames nearly half… │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [30]:
feature_df['political_stance_score'].value_counts()

shape: (5, 2)
┌────────────────────────┬───────┐
│ political_stance_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 2                      ┆ 8     │
│ 4                      ┆ 6     │
│ 5                      ┆ 3     │
│ 3                      ┆ 11    │
│ 1                      ┆ 4     │
└────────────────────────┴───────┘

In [31]:
feature_df = feature_df_dict['sentiment_score']
feature_df

shape: (32, 3)
┌────────────┬─────────────────┬─────────────────────────────────┐
│ comment_id ┆ sentiment_score ┆ reasoning_sentiment_score       │
│ ---        ┆ ---             ┆ ---                             │
│ str        ┆ f64             ┆ str                             │
╞════════════╪═════════════════╪═════════════════════════════════╡
│ ndj18f6    ┆ -0.4            ┆ The comment uses a defensive t… │
│ njalw5c    ┆ -0.3            ┆ The comment expresses a mix of… │
│ nm4anua    ┆ -0.4            ┆ The comment acknowledges a con… │
│ nja4ar2    ┆ -0.5            ┆ The comment highlights serious… │
│ njd5jxd    ┆ -0.6            ┆ The comment expresses a sense … │
│ …          ┆ …               ┆ …                               │
│ njaced6    ┆ -0.5            ┆ The comment expresses criticis… │
│ njetwvu    ┆ -0.4            ┆ The comment employs sarcasm an… │
│ njamm7j    ┆ -0.8            ┆ The comment expresses deep fru… │
│ nm5s9n9    ┆ -0.9            ┆ The comment expresses extreme … │
│ nm3so23    ┆ -0.9            ┆ The language describes total e… │
└────────────┴─────────────────┴─────────────────────────────────┘

In [32]:
feature_df['sentiment_score'].value_counts()

shape: (9, 2)
┌─────────────────┬───────┐
│ sentiment_score ┆ count │
│ ---             ┆ ---   │
│ f64             ┆ u32   │
╞═════════════════╪═══════╡
│ -0.9            ┆ 2     │
│ -0.6            ┆ 4     │
│ -0.7            ┆ 1     │
│ -0.3            ┆ 2     │
│ 0.0             ┆ 2     │
│ 0.2             ┆ 1     │
│ -0.4            ┆ 11    │
│ -0.5            ┆ 6     │
│ -0.8            ┆ 3     │
└─────────────────┴───────┘