In [24]:
import os
import polars as pl

In [25]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')

feature_df_dict = {}
for filename in os.listdir(features_dir):
    name, extension = os.path.splitext(filename) 
    if 'content_relevance_score' not in name and extension == '.parquet':
        path = os.path.join(features_dir, filename)
        feature_df_dict[filename.split('.')[0]] = pl.read_parquet(path)

In [26]:
feature_df_dict.keys()

dict_keys(['argument_quality_score', 'discourse_tone_score', 'dominant_frame_score', 'political_stance_score', 'sentiment_score'])

In [27]:
feature_df = feature_df_dict['argument_quality_score']
feature_df

shape: (38, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ argument_quality_score ┆ reasoning_argument_quality_sco… │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ i64                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ mz95nge    ┆ 4                      ┆ The comment provides specific … │
│ nbrolim    ┆ 2                      ┆ The comment presents a basic o… │
│ mp8psww    ┆ 4                      ┆ The comment provides a well-st… │
│ mx7t4i5    ┆ 2                      ┆ The comment presents a specula… │
│ mafo8vw    ┆ 4                      ┆ The text presents a nuanced ex… │
│ …          ┆ …                      ┆ …                               │
│ mhggqsg    ┆ 3                      ┆ The comment provides a clear o… │
│ neg2p2m    ┆ 2                      ┆ The text presents a highly cha… │
│ mxpwqyc    ┆ 2                      ┆ The text presents a clear opin… │
│ msm44ft    ┆ 1                      ┆ The comment presents a series … │
│ n61rlpg    ┆ 3                      ┆ The comment presents a moderat… │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [28]:
feature_df['argument_quality_score'].value_counts().sort('count', descending=True)

shape: (4, 2)
┌────────────────────────┬───────┐
│ argument_quality_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 2                      ┆ 17    │
│ 4                      ┆ 7     │
│ 1                      ┆ 7     │
│ 3                      ┆ 7     │
└────────────────────────┴───────┘

In [29]:
feature_df = feature_df_dict['discourse_tone_score']
feature_df

shape: (38, 3)
┌────────────┬──────────────────────┬─────────────────────────────────┐
│ comment_id ┆ discourse_tone_score ┆ reasoning_discourse_tone_score  │
│ ---        ┆ ---                  ┆ ---                             │
│ str        ┆ str                  ┆ str                             │
╞════════════╪══════════════════════╪═════════════════════════════════╡
│ mz95nge    ┆ Emotional            ┆ The user expresses strong emot… │
│ nbrolim    ┆ Analytical           ┆ The user presents a condition … │
│ mp8psww    ┆ Informative          ┆ The user provides practical ad… │
│ mx7t4i5    ┆ Emotional            ┆ The user expresses a bleak out… │
│ mafo8vw    ┆ Emotional            ┆ The user expresses personal ex… │
│ …          ┆ …                    ┆ …                               │
│ mhggqsg    ┆ Analytical           ┆ The user provides a factual ob… │
│ neg2p2m    ┆ Emotional            ┆ The user expresses strong emot… │
│ mxpwqyc    ┆ Hostile              ┆ The comment expresses aggressi… │
│ msm44ft    ┆ Hostile              ┆ The user expresses aggressive … │
│ n61rlpg    ┆ Hostile              ┆ The user expresses frustration… │
└────────────┴──────────────────────┴─────────────────────────────────┘

In [30]:
feature_df['discourse_tone_score'].value_counts().sort('count', descending=True)

shape: (5, 2)
┌──────────────────────┬───────┐
│ discourse_tone_score ┆ count │
│ ---                  ┆ ---   │
│ str                  ┆ u32   │
╞══════════════════════╪═══════╡
│ Emotional            ┆ 15    │
│ Analytical           ┆ 11    │
│ Hostile              ┆ 10    │
│ Informative          ┆ 1     │
│ Sarcastic            ┆ 1     │
└──────────────────────┴───────┘

In [31]:
feature_df = feature_df_dict['dominant_frame_score']
feature_df

shape: (38, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ dominant_frame_score   ┆ reasoning_dominant_frame_score  │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ str                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ mz95nge    ┆ Security/Military      ┆ The text primarily discusses m… │
│ nbrolim    ┆ Geopolitical/Political ┆ The focus is on the attributes… │
│ mp8psww    ┆ Humanitarian/Legal     ┆ The text emphasizes personal f… │
│ mx7t4i5    ┆ Humanitarian/Legal     ┆ The text discusses the potenti… │
│ mafo8vw    ┆ Humanitarian/Legal     ┆ The text discusses experiences… │
│ …          ┆ …                      ┆ …                               │
│ mhggqsg    ┆ Humanitarian/Legal     ┆ The comment discusses the acti… │
│ neg2p2m    ┆ Humanitarian/Legal     ┆ The text draws parallels betwe… │
│ mxpwqyc    ┆ Security/Military      ┆ The text emphasizes the influe… │
│ msm44ft    ┆ Security/Military      ┆ The text primarily discusses m… │
│ n61rlpg    ┆ Humanitarian/Legal     ┆ The text discusses the complex… │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [32]:
feature_df['dominant_frame_score'].value_counts().sort('count', descending=True)

shape: (4, 2)
┌────────────────────────┬───────┐
│ dominant_frame_score   ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ Humanitarian/Legal     ┆ 23    │
│ Security/Military      ┆ 7     │
│ Geopolitical/Political ┆ 6     │
│ Media/Narrative        ┆ 2     │
└────────────────────────┴───────┘

In [33]:
feature_df = feature_df_dict['political_stance_score']
feature_df

shape: (38, 3)
┌────────────┬────────────────────────┬─────────────────────────────────┐
│ comment_id ┆ political_stance_score ┆ reasoning_political_stance_sco… │
│ ---        ┆ ---                    ┆ ---                             │
│ str        ┆ i64                    ┆ str                             │
╞════════════╪════════════════════════╪═════════════════════════════════╡
│ mz95nge    ┆ 4                      ┆ The user reacts with alarm ('t… │
│ nbrolim    ┆ 2                      ┆ The comment implies that any l… │
│ mp8psww    ┆ 2                      ┆ The comment encourages involve… │
│ mx7t4i5    ┆ 3                      ┆ The comment presents a bleak o… │
│ mafo8vw    ┆ 4                      ┆ The comment addresses the comp… │
│ …          ┆ …                      ┆ …                               │
│ mhggqsg    ┆ 3                      ┆ The comment focuses on the act… │
│ neg2p2m    ┆ 5                      ┆ The comment strongly condemns … │
│ mxpwqyc    ┆ 2                      ┆ The comment dismisses the orig… │
│ msm44ft    ┆ 1                      ┆ The comment questions the mora… │
│ n61rlpg    ┆ 2                      ┆ The comment critiques the inco… │
└────────────┴────────────────────────┴─────────────────────────────────┘

In [34]:
feature_df['political_stance_score'].value_counts().sort('count', descending=True)

shape: (5, 2)
┌────────────────────────┬───────┐
│ political_stance_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 4                      ┆ 12    │
│ 2                      ┆ 8     │
│ 1                      ┆ 8     │
│ 5                      ┆ 6     │
│ 3                      ┆ 4     │
└────────────────────────┴───────┘

In [35]:
feature_df = feature_df_dict['sentiment_score']
feature_df

shape: (38, 3)
┌────────────┬─────────────────┬─────────────────────────────────┐
│ comment_id ┆ sentiment_score ┆ reasoning_sentiment_score       │
│ ---        ┆ ---             ┆ ---                             │
│ str        ┆ f64             ┆ str                             │
╞════════════╪═════════════════╪═════════════════════════════════╡
│ mz95nge    ┆ -0.7            ┆ The language expresses deep pe… │
│ nbrolim    ┆ 0.0             ┆ The tone is neutral and factua… │
│ mp8psww    ┆ 0.4             ┆ The text expresses a sense of … │
│ mx7t4i5    ┆ 0.2             ┆ The language expresses a mix o… │
│ mafo8vw    ┆ -0.5            ┆ The text expresses frustration… │
│ …          ┆ …               ┆ …                               │
│ mhggqsg    ┆ 0.0             ┆ The language is factual and ob… │
│ neg2p2m    ┆ -0.8            ┆ The language expresses extreme… │
│ mxpwqyc    ┆ -0.8            ┆ The language expresses extreme… │
│ msm44ft    ┆ -0.5            ┆ The language expresses deep fr… │
│ n61rlpg    ┆ -0.5            ┆ The text expresses frustration… │
└────────────┴─────────────────┴─────────────────────────────────┘

In [36]:
feature_df['sentiment_score'].value_counts().sort('count', descending=True)

shape: (10, 2)
┌─────────────────┬───────┐
│ sentiment_score ┆ count │
│ ---             ┆ ---   │
│ f64             ┆ u32   │
╞═════════════════╪═══════╡
│ -0.5            ┆ 11    │
│ -0.8            ┆ 8     │
│ -0.4            ┆ 5     │
│ -0.6            ┆ 5     │
│ 0.4             ┆ 3     │
│ 0.0             ┆ 2     │
│ -0.9            ┆ 1     │
│ -1.0            ┆ 1     │
│ 0.2             ┆ 1     │
│ -0.7            ┆ 1     │
└─────────────────┴───────┘