In [1]:
import os
import polars as pl

In [6]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')

feature_df_dict = {}
for filename in os.listdir(features_dir):
    name, extension = os.path.splitext(filename) 
    if 'content_relevance_score' not in name and extension == '.parquet':
        path = os.path.join(features_dir, filename)
        feature_df_dict[filename.split('.')[0]] = pl.read_parquet(path)

In [13]:
feature_df_dict.keys()

dict_keys(['argument_quality_score', 'discourse_tone', 'dominant_frame', 'embeddings', 'political_stance', 'sentiment_score'])

In [8]:
feature_df = feature_df_dict['argument_quality_score']
feature_df

shape: (23, 2)
┌────────────┬────────────────────────┐
│ comment_id ┆ argument_quality_score │
│ ---        ┆ ---                    │
│ str        ┆ i64                    │
╞════════════╪════════════════════════╡
│ njalw5c    ┆ 2                      │
│ nm4anua    ┆ 2                      │
│ nja4ar2    ┆ 3                      │
│ nm3pvch    ┆ 2                      │
│ n5yci2x    ┆ 2                      │
│ …          ┆ …                      │
│ n5y0puk    ┆ 1                      │
│ njaced6    ┆ 3                      │
│ njetwvu    ┆ 1                      │
│ njamm7j    ┆ 3                      │
│ nm3so23    ┆ 1                      │
└────────────┴────────────────────────┘

In [9]:
feature_df['argument_quality_score'].value_counts()

shape: (4, 2)
┌────────────────────────┬───────┐
│ argument_quality_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 3                      ┆ 5     │
│ 1                      ┆ 8     │
│ 2                      ┆ 8     │
│ 4                      ┆ 2     │
└────────────────────────┴───────┘

In [10]:
feature_df = feature_df_dict['discourse_tone']
feature_df

shape: (23, 2)
┌────────────┬────────────────┐
│ comment_id ┆ discourse_tone │
│ ---        ┆ ---            │
│ str        ┆ str            │
╞════════════╪════════════════╡
│ njalw5c    ┆ Analytical     │
│ nm4anua    ┆ Sarcastic      │
│ nja4ar2    ┆ Informative    │
│ nm3pvch    ┆ Analytical     │
│ n5yci2x    ┆ Hostile        │
│ …          ┆ …              │
│ n5y0puk    ┆ Hostile        │
│ njaced6    ┆ Analytical     │
│ njetwvu    ┆ Sarcastic      │
│ njamm7j    ┆ Hostile        │
│ nm3so23    ┆ Hostile        │
└────────────┴────────────────┘

In [11]:
feature_df['discourse_tone'].value_counts()

shape: (5, 2)
┌────────────────┬───────┐
│ discourse_tone ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Sarcastic      ┆ 2     │
│ Hostile        ┆ 10    │
│ Informative    ┆ 2     │
│ Emotional      ┆ 4     │
│ Analytical     ┆ 5     │
└────────────────┴───────┘

In [14]:
feature_df = feature_df_dict['dominant_frame']
feature_df

shape: (23, 2)
┌────────────┬────────────────────────┐
│ comment_id ┆ dominant_frame         │
│ ---        ┆ ---                    │
│ str        ┆ str                    │
╞════════════╪════════════════════════╡
│ njalw5c    ┆ Geopolitical/Political │
│ nm4anua    ┆ Humanitarian/Legal     │
│ nja4ar2    ┆ Humanitarian/Legal     │
│ nm3pvch    ┆ Humanitarian/Legal     │
│ n5yci2x    ┆ Humanitarian/Legal     │
│ …          ┆ …                      │
│ n5y0puk    ┆ Security/Military      │
│ njaced6    ┆ Historical/Religious   │
│ njetwvu    ┆ Geopolitical/Political │
│ njamm7j    ┆ Security/Military      │
│ nm3so23    ┆ Humanitarian/Legal     │
└────────────┴────────────────────────┘

In [15]:
feature_df['dominant_frame'].value_counts()

shape: (4, 2)
┌────────────────────────┬───────┐
│ dominant_frame         ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ Security/Military      ┆ 4     │
│ Humanitarian/Legal     ┆ 9     │
│ Historical/Religious   ┆ 3     │
│ Geopolitical/Political ┆ 7     │
└────────────────────────┴───────┘

In [16]:
feature_df = feature_df_dict['political_stance']
feature_df

shape: (23, 2)
┌────────────┬──────────────────┐
│ comment_id ┆ political_stance │
│ ---        ┆ ---              │
│ str        ┆ i64              │
╞════════════╪══════════════════╡
│ njalw5c    ┆ 2                │
│ nm4anua    ┆ 2                │
│ nja4ar2    ┆ 2                │
│ nm3pvch    ┆ 3                │
│ n5yci2x    ┆ 1                │
│ …          ┆ …                │
│ n5y0puk    ┆ 4                │
│ njaced6    ┆ 2                │
│ njetwvu    ┆ 4                │
│ njamm7j    ┆ 4                │
│ nm3so23    ┆ 1                │
└────────────┴──────────────────┘

In [17]:
feature_df['political_stance'].value_counts()

shape: (5, 2)
┌──────────────────┬───────┐
│ political_stance ┆ count │
│ ---              ┆ ---   │
│ i64              ┆ u32   │
╞══════════════════╪═══════╡
│ 3                ┆ 5     │
│ 1                ┆ 5     │
│ 5                ┆ 2     │
│ 2                ┆ 7     │
│ 4                ┆ 4     │
└──────────────────┴───────┘

In [18]:
feature_df = feature_df_dict['sentiment_score']
feature_df

shape: (23, 2)
┌────────────┬─────────────────┐
│ comment_id ┆ sentiment_score │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ njalw5c    ┆ -0.3            │
│ nm4anua    ┆ 0.3             │
│ nja4ar2    ┆ -0.6            │
│ nm3pvch    ┆ 0.1             │
│ n5yci2x    ┆ -0.8            │
│ …          ┆ …               │
│ n5y0puk    ┆ -0.4            │
│ njaced6    ┆ -0.6            │
│ njetwvu    ┆ -0.4            │
│ njamm7j    ┆ -0.8            │
│ nm3so23    ┆ -0.9            │
└────────────┴─────────────────┘

In [19]:
feature_df['sentiment_score'].value_counts()

shape: (9, 2)
┌─────────────────┬───────┐
│ sentiment_score ┆ count │
│ ---             ┆ ---   │
│ f64             ┆ u32   │
╞═════════════════╪═══════╡
│ 0.1             ┆ 1     │
│ 0.3             ┆ 1     │
│ 0.0             ┆ 1     │
│ -0.4            ┆ 4     │
│ -0.9            ┆ 1     │
│ -0.8            ┆ 4     │
│ -0.6            ┆ 8     │
│ -0.3            ┆ 2     │
│ -0.7            ┆ 1     │
└─────────────────┴───────┘