In [12]:
import os
import polars as pl

In [13]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
features_dir = os.path.join(project_path, 'data', 'features')

feature_df_dict = {}
for filename in os.listdir(features_dir):
    if 'content_relevance_score' not in filename:
        path = os.path.join(features_dir, filename)
        feature_df_dict[filename.split('.')[0]] = pl.read_parquet(path)

In [14]:
feature_df_dict.keys()

dict_keys(['argument_quality_score', 'discourse_tone', 'dominant_frame', 'political_stance', 'sentiment_score'])

In [15]:
feature_df = feature_df_dict['argument_quality_score']
feature_df

shape: (13, 2)
┌────────────┬────────────────────────┐
│ comment_id ┆ argument_quality_score │
│ ---        ┆ ---                    │
│ str        ┆ i64                    │
╞════════════╪════════════════════════╡
│ njay3a4    ┆ 1                      │
│ nja48ig    ┆ 2                      │
│ nj9gjve    ┆ 4                      │
│ nj9230c    ┆ 2                      │
│ njcxski    ┆ 2                      │
│ …          ┆ …                      │
│ n5yzlmr    ┆ 4                      │
│ ndiuv96    ┆ 1                      │
│ ndjc3hu    ┆ 3                      │
│ mwvmrsi    ┆ 3                      │
│ nke2ico    ┆ 2                      │
└────────────┴────────────────────────┘

In [16]:
feature_df['argument_quality_score'].value_counts()

shape: (4, 2)
┌────────────────────────┬───────┐
│ argument_quality_score ┆ count │
│ ---                    ┆ ---   │
│ i64                    ┆ u32   │
╞════════════════════════╪═══════╡
│ 2                      ┆ 5     │
│ 4                      ┆ 2     │
│ 1                      ┆ 4     │
│ 3                      ┆ 2     │
└────────────────────────┴───────┘

In [17]:
feature_df = feature_df_dict['discourse_tone']
feature_df

shape: (13, 2)
┌────────────┬────────────────┐
│ comment_id ┆ discourse_tone │
│ ---        ┆ ---            │
│ str        ┆ str            │
╞════════════╪════════════════╡
│ njay3a4    ┆ Sarcastic      │
│ nja48ig    ┆ Analytical     │
│ nj9gjve    ┆ Analytical     │
│ nj9230c    ┆ Informative    │
│ njcxski    ┆ Informative    │
│ …          ┆ …              │
│ n5yzlmr    ┆ Analytical     │
│ ndiuv96    ┆ Hostile        │
│ ndjc3hu    ┆ Emotional      │
│ mwvmrsi    ┆ Sarcastic      │
│ nke2ico    ┆ Informative    │
└────────────┴────────────────┘

In [18]:
feature_df['discourse_tone'].value_counts()

shape: (5, 2)
┌────────────────┬───────┐
│ discourse_tone ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Analytical     ┆ 3     │
│ Sarcastic      ┆ 2     │
│ Informative    ┆ 3     │
│ Hostile        ┆ 3     │
│ Emotional      ┆ 2     │
└────────────────┴───────┘

In [19]:
feature_df = feature_df_dict['dominant_frame']
feature_df

shape: (13, 2)
┌────────────┬────────────────────────┐
│ comment_id ┆ dominant_frame         │
│ ---        ┆ ---                    │
│ str        ┆ str                    │
╞════════════╪════════════════════════╡
│ njay3a4    ┆ Geopolitical/Political │
│ nja48ig    ┆ Geopolitical/Political │
│ nj9gjve    ┆ Geopolitical/Political │
│ nj9230c    ┆ Geopolitical/Political │
│ njcxski    ┆ Geopolitical/Political │
│ …          ┆ …                      │
│ n5yzlmr    ┆ Security/Military      │
│ ndiuv96    ┆ Geopolitical/Political │
│ ndjc3hu    ┆ Humanitarian/Legal     │
│ mwvmrsi    ┆ Security/Military      │
│ nke2ico    ┆ Security/Military      │
└────────────┴────────────────────────┘

In [20]:
feature_df['dominant_frame'].value_counts()

shape: (3, 2)
┌────────────────────────┬───────┐
│ dominant_frame         ┆ count │
│ ---                    ┆ ---   │
│ str                    ┆ u32   │
╞════════════════════════╪═══════╡
│ Security/Military      ┆ 3     │
│ Geopolitical/Political ┆ 7     │
│ Humanitarian/Legal     ┆ 3     │
└────────────────────────┴───────┘

In [21]:
feature_df = feature_df_dict['political_stance']
feature_df

shape: (13, 2)
┌────────────┬──────────────────┐
│ comment_id ┆ political_stance │
│ ---        ┆ ---              │
│ str        ┆ i64              │
╞════════════╪══════════════════╡
│ njay3a4    ┆ 3                │
│ nja48ig    ┆ 3                │
│ nj9gjve    ┆ 1                │
│ nj9230c    ┆ 4                │
│ njcxski    ┆ 3                │
│ …          ┆ …                │
│ n5yzlmr    ┆ 4                │
│ ndiuv96    ┆ 4                │
│ ndjc3hu    ┆ 2                │
│ mwvmrsi    ┆ 4                │
│ nke2ico    ┆ 4                │
└────────────┴──────────────────┘

In [22]:
feature_df['political_stance'].value_counts()

shape: (4, 2)
┌──────────────────┬───────┐
│ political_stance ┆ count │
│ ---              ┆ ---   │
│ i64              ┆ u32   │
╞══════════════════╪═══════╡
│ 3                ┆ 3     │
│ 4                ┆ 5     │
│ 2                ┆ 2     │
│ 1                ┆ 3     │
└──────────────────┴───────┘

In [23]:
feature_df = feature_df_dict['sentiment_score']
feature_df

shape: (13, 2)
┌────────────┬─────────────────┐
│ comment_id ┆ sentiment_score │
│ ---        ┆ ---             │
│ str        ┆ f64             │
╞════════════╪═════════════════╡
│ njay3a4    ┆ -0.6            │
│ nja48ig    ┆ -0.2            │
│ nj9gjve    ┆ -0.5            │
│ nj9230c    ┆ -0.4            │
│ njcxski    ┆ 0.0             │
│ …          ┆ …               │
│ n5yzlmr    ┆ -0.4            │
│ ndiuv96    ┆ -0.6            │
│ ndjc3hu    ┆ -0.7            │
│ mwvmrsi    ┆ -0.4            │
│ nke2ico    ┆ 0.2             │
└────────────┴─────────────────┘

In [24]:
feature_df['sentiment_score'].value_counts()

shape: (8, 2)
┌─────────────────┬───────┐
│ sentiment_score ┆ count │
│ ---             ┆ ---   │
│ f64             ┆ u32   │
╞═════════════════╪═══════╡
│ -0.5            ┆ 1     │
│ -0.2            ┆ 1     │
│ -0.8            ┆ 1     │
│ -0.7            ┆ 1     │
│ 0.0             ┆ 1     │
│ -0.6            ┆ 4     │
│ -0.4            ┆ 3     │
│ 0.2             ┆ 1     │
└─────────────────┴───────┘