In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')
processed_data_path = os.path.join(processed_data_dir, '04d_processed_data.parquet')

In [3]:
processed_data = pl.read_parquet(processed_data_path)
processed_data

shape: (11, 34)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ comment_b ┆ comment_s ┆ … ┆ discourse ┆ dominant_ ┆ political ┆ sentiment │
│ ---        ┆ ---     ┆ ody       ┆ core      ┆   ┆ _tone     ┆ frame     ┆ _stance   ┆ _score    │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│            ┆         ┆ str       ┆ i64       ┆   ┆ str       ┆ str       ┆ i64       ┆ f64       │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ njalw5c    ┆ 1o5fc5m ┆ Great     ┆ 3         ┆ … ┆ Analytica ┆ Geopoliti ┆ 2         ┆ -0.3      │
│            ┆         ┆ news, but ┆           ┆   ┆ l         ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ as long   ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ as isr…   ┆           ┆   ┆           ┆           ┆           ┆           │
│ nm4anua    ┆ 1ojjtnz ┆ Oh I      ┆ 1         ┆ … ┆ Sarcastic ┆ Humanitar ┆ 2         ┆ 0.2       │
│            ┆         ┆ agree she ┆           ┆   ┆           ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ is bat    ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ shit cra… ┆           ┆   ┆           ┆           ┆           ┆           │
│ nm3pvch    ┆ 1ojjtnz ┆ No, most, ┆ 3         ┆ … ┆ Analytica ┆ Humanitar ┆ 3         ┆ 0.1       │
│            ┆         ┆ like      ┆           ┆   ┆ l         ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ myself,   ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ scrutin…  ┆           ┆   ┆           ┆           ┆           ┆           │
│ nj9xn9e    ┆ 1o5fc5m ┆ Literally ┆ 49        ┆ … ┆ Hostile   ┆ Geopoliti ┆ 3         ┆ -0.6      │
│            ┆         ┆ every     ┆           ┆   ┆           ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ side of   ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ the co…   ┆           ┆   ┆           ┆           ┆           ┆           │
│ nj9m4er    ┆ 1o5c29r ┆ October   ┆ 3         ┆ … ┆ Emotional ┆ Humanitar ┆ 1         ┆ -0.6      │
│            ┆         ┆ 7th       ┆           ┆   ┆           ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ wouldn’t  ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ have      ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ happ…     ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ njc2cav    ┆ 1o5fc5m ┆ And what  ┆ 2         ┆ … ┆ Emotional ┆ Humanitar ┆ 2         ┆ -0.6      │
│            ┆         ┆ do people ┆           ┆   ┆           ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ in Gaza   ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ hav…      ┆           ┆   ┆           ┆           ┆           ┆           │
│ nj9e8nu    ┆ 1o5fc5m ┆ Really?   ┆ 7         ┆ … ┆ Informati ┆ Geopoliti ┆ 3         ┆ 0.0       │
│            ┆         ┆ Please    ┆           ┆   ┆ ve        ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ share     ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ details.… ┆           ┆   ┆           ┆           ┆           ┆           │
│ nja57ei    ┆ 1o5fc5m ┆ No, its   ┆ 4         ┆ … ┆ Hostile   ┆ Geopoliti ┆ 3         ┆ -0.4      │
│            ┆         ┆ that      ┆           ┆   ┆           ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ Netanyahu ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ wanted …  ┆           ┆   ┆           ┆           ┆           ┆           │
│ njetwvu    ┆ 1o5fc5m ┆ So you    ┆ 2         ┆ … ┆ Sarcastic ┆ Geopoliti ┆ 4         ┆ -0.4      │
│            ┆         ┆ claim     ┆           ┆   ┆           ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ Israel    ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ supported ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ njamm7j    ┆ 1o5fc5m ┆ And hamas ┆ 2         ┆ … ┆ Hostile   ┆ Security/ ┆ 4         ┆ -0.8      │
│            ┆         ┆ wastes no ┆           ┆   ┆           ┆ Military  ┆           ┆           │
│            ┆         ┆ time      ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ murde…    ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
processed_data[['argument_quality_score', 'discourse_tone', 'dominant_frame', 'political_stance', 'sentiment_score']]

shape: (11, 5)
┌──────────────────────┬────────────────┬─────────────────────┬──────────────────┬─────────────────┐
│ argument_quality_sco ┆ discourse_tone ┆ dominant_frame      ┆ political_stance ┆ sentiment_score │
│ re                   ┆ ---            ┆ ---                 ┆ ---              ┆ ---             │
│ ---                  ┆ str            ┆ str                 ┆ i64              ┆ f64             │
│ i64                  ┆                ┆                     ┆                  ┆                 │
╞══════════════════════╪════════════════╪═════════════════════╪══════════════════╪═════════════════╡
│ 2                    ┆ Analytical     ┆ Geopolitical/Politi ┆ 2                ┆ -0.3            │
│                      ┆                ┆ cal                 ┆                  ┆                 │
│ 2                    ┆ Sarcastic      ┆ Humanitarian/Legal  ┆ 2                ┆ 0.2             │
│ 2                    ┆ Analytical     ┆ Humanitarian/Legal  ┆ 3                ┆ 0.1             │
│ 1                    ┆ Hostile        ┆ Geopolitical/Politi ┆ 3                ┆ -0.6            │
│                      ┆                ┆ cal                 ┆                  ┆                 │
│ 3                    ┆ Emotional      ┆ Humanitarian/Legal  ┆ 1                ┆ -0.6            │
│ …                    ┆ …              ┆ …                   ┆ …                ┆ …               │
│ 3                    ┆ Emotional      ┆ Humanitarian/Legal  ┆ 2                ┆ -0.6            │
│ 1                    ┆ Informative    ┆ Geopolitical/Politi ┆ 3                ┆ 0.0             │
│                      ┆                ┆ cal                 ┆                  ┆                 │
│ 2                    ┆ Hostile        ┆ Geopolitical/Politi ┆ 3                ┆ -0.4            │
│                      ┆                ┆ cal                 ┆                  ┆                 │
│ 2                    ┆ Sarcastic      ┆ Geopolitical/Politi ┆ 4                ┆ -0.4            │
│                      ┆                ┆ cal                 ┆                  ┆                 │
│ 3                    ┆ Hostile        ┆ Security/Military   ┆ 4                ┆ -0.8            │
└──────────────────────┴────────────────┴─────────────────────┴──────────────────┴─────────────────┘