In [1]:
import os
import polars as pl

In [2]:
script_path = os.getcwd()
project_path = os.path.join(script_path, '..')
processed_data_dir = os.path.join(project_path, 'data', 'processed_data')
processed_data_path = os.path.join(processed_data_dir, '04d_processed_data.parquet')

In [3]:
processed_data = pl.read_parquet(processed_data_path)
processed_data.head()

shape: (5, 25)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ comment_b ┆ comment_s ┆ … ┆ discourse ┆ dominant_ ┆ political ┆ sentiment │
│ ---        ┆ ---     ┆ ody       ┆ core      ┆   ┆ _tone_sco ┆ frame_sco ┆ _stance_s ┆ _score    │
│ str        ┆ str     ┆ ---       ┆ ---       ┆   ┆ re        ┆ re        ┆ core      ┆ ---       │
│            ┆         ┆ str       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ f64       │
│            ┆         ┆           ┆           ┆   ┆ str       ┆ str       ┆ i64       ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ mz95nge    ┆ 1lhyjk6 ┆ This is   ┆ 15        ┆ … ┆ Emotional ┆ Security/ ┆ 4         ┆ -0.7      │
│            ┆         ┆ fucking   ┆           ┆   ┆           ┆ Military  ┆           ┆           │
│            ┆         ┆ terrible  ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ news.…    ┆           ┆   ┆           ┆           ┆           ┆           │
│ nbrolim    ┆ 1n5ak70 ┆ It would  ┆ -3        ┆ … ┆ Analytica ┆ Geopoliti ┆ 2         ┆ 0.0       │
│            ┆         ┆ definitel ┆           ┆   ┆ l         ┆ cal/Polit ┆           ┆           │
│            ┆         ┆ y include ┆           ┆   ┆           ┆ ical      ┆           ┆           │
│            ┆         ┆ ha…       ┆           ┆   ┆           ┆           ┆           ┆           │
│ mp8psww    ┆ 1k8jzuf ┆ You       ┆ 3         ┆ … ┆ Informati ┆ Humanitar ┆ 2         ┆ 0.4       │
│            ┆         ┆ should    ┆           ┆   ┆ ve        ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ get       ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ involved  ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ in an …   ┆           ┆   ┆           ┆           ┆           ┆           │
│ mx7t4i5    ┆ 1l8j2nm ┆ This ends ┆ 3         ┆ … ┆ Emotional ┆ Humanitar ┆ 3         ┆ 0.2       │
│            ┆         ┆ in one of ┆           ┆   ┆           ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ four ways ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ …         ┆           ┆   ┆           ┆           ┆           ┆           │
│ mafo8vw    ┆ 1ievoe9 ┆ Also the  ┆ 8         ┆ … ┆ Emotional ┆ Humanitar ┆ 4         ┆ -0.5      │
│            ┆         ┆ Holocaust ┆           ┆   ┆           ┆ ian/Legal ┆           ┆           │
│            ┆         ┆ inversion ┆           ┆   ┆           ┆           ┆           ┆           │
│            ┆         ┆ a…        ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
processed_data[['comment_id', 'post_id', 'text_content', 'argument_quality_score', 'discourse_tone_score', 'dominant_frame_score', 'political_stance_score', 'sentiment_score']]

shape: (38, 8)
┌────────────┬─────────┬────────────┬────────────┬────────────┬────────────┬───────────┬───────────┐
│ comment_id ┆ post_id ┆ text_conte ┆ argument_q ┆ discourse_ ┆ dominant_f ┆ political ┆ sentiment │
│ ---        ┆ ---     ┆ nt         ┆ uality_sco ┆ tone_score ┆ rame_score ┆ _stance_s ┆ _score    │
│ str        ┆ str     ┆ ---        ┆ re         ┆ ---        ┆ ---        ┆ core      ┆ ---       │
│            ┆         ┆ str        ┆ ---        ┆ str        ┆ str        ┆ ---       ┆ f64       │
│            ┆         ┆            ┆ i64        ┆            ┆            ┆ i64       ┆           │
╞════════════╪═════════╪════════════╪════════════╪════════════╪════════════╪═══════════╪═══════════╡
│ mz95nge    ┆ 1lhyjk6 ┆ Post       ┆ 4          ┆ Emotional  ┆ Security/M ┆ 4         ┆ -0.7      │
│            ┆         ┆ Title:     ┆            ┆            ┆ ilitary    ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Operation  ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Rising …   ┆            ┆            ┆            ┆           ┆           │
│ nbrolim    ┆ 1n5ak70 ┆ Post       ┆ 2          ┆ Analytical ┆ Geopolitic ┆ 2         ┆ 0.0       │
│            ┆         ┆ Title:     ┆            ┆            ┆ al/Politic ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆ al         ┆           ┆           │
│            ┆         ┆ Post-war   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ plan see…  ┆            ┆            ┆            ┆           ┆           │
│ mp8psww    ┆ 1k8jzuf ┆ Post       ┆ 4          ┆ Informativ ┆ Humanitari ┆ 2         ┆ 0.4       │
│            ┆         ┆ Title:     ┆            ┆ e          ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Being an   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ ally       ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Po…        ┆            ┆            ┆            ┆           ┆           │
│ mx7t4i5    ┆ 1l8j2nm ┆ Post       ┆ 2          ┆ Emotional  ┆ Humanitari ┆ 3         ┆ 0.2       │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Is         ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Israel's   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Aid a…     ┆            ┆            ┆            ┆           ┆           │
│ mafo8vw    ┆ 1ievoe9 ┆ Post       ┆ 4          ┆ Emotional  ┆ Humanitari ┆ 4         ┆ -0.5      │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Doing      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ research   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ fo…        ┆            ┆            ┆            ┆           ┆           │
│ …          ┆ …       ┆ …          ┆ …          ┆ …          ┆ …          ┆ …         ┆ …         │
│ mhggqsg    ┆ 1j9upry ┆ Post       ┆ 3          ┆ Analytical ┆ Humanitari ┆ 3         ┆ 0.0       │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Houthis    ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ announce … ┆            ┆            ┆            ┆           ┆           │
│ neg2p2m    ┆ 1nhnxb5 ┆ Post       ┆ 2          ┆ Emotional  ┆ Humanitari ┆ 5         ┆ -0.8      │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ A quick    ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ thought e… ┆            ┆            ┆            ┆           ┆           │
│ mxpwqyc    ┆ 1lasn8p ┆ Post       ┆ 2          ┆ Hostile    ┆ Security/M ┆ 2         ┆ -0.8      │
│            ┆         ┆ Title:     ┆            ┆            ┆ ilitary    ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Gen Z      ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ cheering   ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ on…        ┆            ┆            ┆            ┆           ┆           │
│ msm44ft    ┆ 1knysu3 ┆ Post       ┆ 1          ┆ Hostile    ┆ Security/M ┆ 1         ┆ -0.5      │
│            ┆         ┆ Title:     ┆            ┆            ┆ ilitary    ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Operation: ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Gideon…    ┆            ┆            ┆            ┆           ┆           │
│ n61rlpg    ┆ 1mdhogk ┆ Post       ┆ 3          ┆ Hostile    ┆ Humanitari ┆ 2         ┆ -0.5      │
│            ┆         ┆ Title:     ┆            ┆            ┆ an/Legal   ┆           ┆           │
│            ┆         ┆            ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Why is     ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ Judaism    ┆            ┆            ┆            ┆           ┆           │
│            ┆         ┆ an…        ┆            ┆            ┆            ┆           ┆           │
└────────────┴─────────┴────────────┴────────────┴────────────┴────────────┴───────────┴───────────┘